import{randomUUID}from"node:crypto";import{serve}from"@hono/node-server";import{Hono}from"hono";import{context,health,pool}from"@raeburn/service-kit";
import{googleFreeBusy,googleCreateEvent}from"@raeburn/connector-google-calendar";
import{gmailSend}from"@raeburn/connector-gmail";
import{microsoftSchedule,microsoftCreateEvent}from"@raeburn/connector-microsoft-calendar";
import{microsoftSendMail}from"@raeburn/connector-microsoft-email";
import{signedWebhook}from"@raeburn/connector-webhook";

const app=new Hono();
const builtIns=[
 {provider:"google-jobs",status:"READY",mode:"structured-data",message:"Published vacancies expose JobPosting structured data on canonical careers pages."},
 {provider:"json-feed",status:"READY",mode:"feed",message:"Public JSON vacancy feed is available."},
 {provider:"xml-feed",status:"READY",mode:"feed",message:"Public XML vacancy feed is available."},
 {provider:"csv-feed",status:"READY",mode:"feed",message:"Public CSV vacancy feed is available."},
 {provider:"google-calendar",status:"NOT_CONFIGURED",mode:"oauth",message:"Requires Google OAuth token configuration."},
 {provider:"gmail",status:"NOT_CONFIGURED",mode:"oauth",message:"Requires Google OAuth token configuration."},
 {provider:"microsoft-calendar",status:"NOT_CONFIGURED",mode:"oauth",message:"Requires Microsoft Graph OAuth token configuration."},
 {provider:"microsoft-email",status:"NOT_CONFIGURED",mode:"oauth",message:"Requires Microsoft Graph OAuth token configuration."},
 {provider:"webhook",status:"NOT_CONFIGURED",mode:"webhook",message:"Generic signed REST handoff for HRIS, payroll, e-sign, Slack/Teams and other approved systems."},
 {provider:"indeed",status:"NOT_CONFIGURED",mode:"partner",message:"Requires approved provider integration or feed arrangement before publication can be confirmed."},
 {provider:"linkedin",status:"NOT_CONFIGURED",mode:"partner",message:"Requires approved provider integration before publication can be confirmed."},
 {provider:"adzuna",status:"NOT_CONFIGURED",mode:"partner",message:"Requires provider credentials/integration before publication can be confirmed."},
 {provider:"jooble",status:"NOT_CONFIGURED",mode:"partner",message:"Requires provider credentials/integration before publication can be confirmed."}
];

app.get("/health",async c=>c.json(await health("integrations")));
app.get("/v1/integrations",async c=>{const x=context(c.req.raw.headers);const configured=(await pool.query("select provider,status,config,updated_at from integration_connections where tenant_id=$1",[x.tenantId])).rows;const byProvider=new Map(configured.map((r:any)=>[r.provider,r]));return c.json(builtIns.map(base=>({...base,...(byProvider.get(base.provider)||{})})).concat(configured.filter((r:any)=>!builtIns.some(b=>b.provider===r.provider))));});
app.put("/v1/integrations/:provider",async c=>{const x=context(c.req.raw.headers),provider=c.req.param("provider"),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into integration_connections(id,tenant_id,provider,status,config) values($1,$2,$3,$4,$5::jsonb) on conflict(tenant_id,provider) do update set status=excluded.status,config=excluded.config,updated_at=now()",[id,x.tenantId,provider,b.status||"CONFIGURED",JSON.stringify(b.config||{})]);return c.json({provider,status:b.status||"CONFIGURED"});});
app.post("/v1/integrations/:provider/actions/:action",async c=>{const x=context(c.req.raw.headers),provider=c.req.param("provider"),action=c.req.param("action"),body:any=await c.req.json(),connection=(await pool.query("select * from integration_connections where tenant_id=$1 and provider=$2",[x.tenantId,provider])).rows[0],id=randomUUID();if(!connection||connection.status==="DISCONNECTED")return c.json({code:"NOT_CONFIGURED",message:"Integration is not configured"},409);const config=connection.config||{},token=config.accessTokenEnv?process.env[String(config.accessTokenEnv)]:undefined,secret=config.secretEnv?process.env[String(config.secretEnv)]:undefined;await pool.query("insert into integration_actions(id,tenant_id,provider,action,status,request_meta,correlation_id) values($1,$2,$3,$4,'RUNNING',$5::jsonb,$6)",[id,x.tenantId,provider,action,JSON.stringify({keys:Object.keys(body||{})}),x.correlationId]);try{let result:any;if(provider==="google-calendar"&&action==="free-busy"){if(!token)throw new Error("Google access token environment variable is unavailable");result=await googleFreeBusy(token,body);}else if(provider==="google-calendar"&&action==="create-event"){if(!token)throw new Error("Google access token environment variable is unavailable");result=await googleCreateEvent(token,body.calendarId||"primary",body.event);}else if(provider==="gmail"&&action==="send"){if(!token)throw new Error("Gmail access token environment variable is unavailable");result=await gmailSend(token,body);}else if(provider==="microsoft-calendar"&&action==="free-busy"){if(!token)throw new Error("Microsoft access token environment variable is unavailable");result=await microsoftSchedule(token,body.schedules,body.start,body.end,body.timeZone||"UTC");}else if(provider==="microsoft-calendar"&&action==="create-event"){if(!token)throw new Error("Microsoft access token environment variable is unavailable");result=await microsoftCreateEvent(token,body.event);}else if(provider==="microsoft-email"&&action==="send"){if(!token)throw new Error("Microsoft access token environment variable is unavailable");result=await microsoftSendMail(token,body);}else if(provider==="webhook"&&action==="send"){if(!config.url)throw new Error("Webhook URL is not configured");result=await signedWebhook(config.url,body.payload,secret);}else return c.json({code:"UNSUPPORTED_ACTION",message:"Provider action is not supported"},400);await pool.query("update integration_actions set status='SUCCEEDED',response_meta=$2::jsonb,completed_at=now() where id=$1",[id,JSON.stringify({ok:true})]);return c.json({id,status:"SUCCEEDED",result});}catch(err){const message=err instanceof Error?err.message:String(err);await pool.query("update integration_actions set status='FAILED',last_error=$2,completed_at=now() where id=$1",[id,message]);return c.json({id,status:"FAILED",error:message},502);}});
app.get("/v1/integrations/actions",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from integration_actions where tenant_id=$1 order by created_at desc limit 250",[x.tenantId])).rows);});
serve({fetch:app.fetch,port:Number(process.env.PORT||4123)});