import{randomUUID}from"node:crypto";import{serve}from"@hono/node-server";import{Hono}from"hono";import{z}from"zod";import{context,health,pool}from"@raeburn/service-kit";
const app=new Hono(),CANDIDATES=process.env.CANDIDATES_URL||"http://localhost:4102";
const Task=z.enum(["parse_cv","summarise_cv","evidence_against_requirements","interview_questions","draft_communication","summarise_notes","draft_job_description","review_job_description","normalise_skills","search_query","talent_pool_suggestions","similar_candidates","similar_roles","funnel_anomaly","source_performance","workload_summary","needs_attention"]);
const Request=z.object({task:Task,context:z.record(z.string(),z.unknown()),promptVersion:z.string().default("v1")});
async function runAdvice(tenantId:string,actor:string|null,b:z.infer<typeof Request>){const id=randomUUID(),endpoint=process.env.AI_ADVISORY_ENDPOINT,provider=process.env.AI_PROVIDER||"custom",model=process.env.AI_MODEL||"unspecified";await pool.query("insert into ai_runs(id,tenant_id,task,provider,model,prompt_version,input_meta,status,requested_by) values($1,$2,$3,$4,$5,$6,$7::jsonb,'RUNNING',$8)",[id,tenantId,b.task,provider,model,b.promptVersion,JSON.stringify({keys:Object.keys(b.context)}),actor]);if(!endpoint){await pool.query("update ai_runs set status='DISABLED',last_error='Provider not configured',completed_at=now() where id=$1",[id]);return{id,status:"disabled",advisoryOnly:true,message:"AI advisory provider is not configured. Core recruitment remains available."};}try{const auth=process.env.AI_ADVISORY_TOKEN?"Bearer "+process.env.AI_ADVISORY_TOKEN:"",r=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json","authorization":auth},body:JSON.stringify(b),signal:AbortSignal.timeout(Number(process.env.AI_TIMEOUT_MS||45000))});if(!r.ok)throw new Error("AI provider returned "+r.status);const result=await r.json();await pool.query("update ai_runs set status='SUCCEEDED',result=$2::jsonb,completed_at=now() where id=$1",[id,JSON.stringify(result)]);return{id,status:"ok",advisoryOnly:true,provider,model,promptVersion:b.promptVersion,result};}catch(err){const message=err instanceof Error?err.message:String(err);await pool.query("update ai_runs set status='FAILED',last_error=$2,completed_at=now() where id=$1",[id,message]);return{id,status:"unavailable",advisoryOnly:true,error:message};}}
app.get("/health",async c=>c.json(await health("intelligence")));
app.post("/v1/intelligence/advice",async c=>{const x=context(c.req.raw.headers),b=Request.parse(await c.req.json()),result=await runAdvice(x.tenantId,c.req.header("x-actor")||null,b);return c.json(result,result.status==="ok"?200:503);});
app.get("/v1/intelligence/runs",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select id,task,provider,model,prompt_version,status,advisory_only,requested_by,created_at,completed_at,last_error from ai_runs where tenant_id=$1 order by created_at desc limit 250",[x.tenantId])).rows);});
app.get("/v1/intelligence/candidates/:id/extractions",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from candidate_extractions where tenant_id=$1 and candidate_id=$2 order by created_at desc",[x.tenantId,c.req.param("id")])).rows);});
app.post("/v1/intelligence/extractions/:id/approve",async c=>{const x=context(c.req.raw.headers),id=c.req.param("id"),row=(await pool.query("select * from candidate_extractions where tenant_id=$1 and id=$2",[x.tenantId,id])).rows[0];if(!row)return c.json({code:"NOT_FOUND",message:"Extraction not found"},404);if(row.status!=="REVIEW_REQUIRED")return c.json({code:"INVALID_STATE",message:"Extraction is not awaiting review"},409);const r=await fetch(CANDIDATES+"/v1/candidates/"+row.candidate_id+"/profile",{method:"PATCH",headers:{"content-type":"application/json","x-tenant-id":x.tenantId,"x-correlation-id":x.correlationId,"x-actor":c.req.header("x-actor")||"intelligence-review"},body:JSON.stringify({profile:row.extraction.profile||row.extraction,tags:row.extraction.tags||undefined})});if(!r.ok)return c.json({code:"CANDIDATE_UPDATE_FAILED",message:"Could not apply approved extraction"},502);await pool.query("update candidate_extractions set status='APPROVED',reviewed_by=$3,reviewed_at=now() where tenant_id=$1 and id=$2",[x.tenantId,id,c.req.header("x-actor")||null]);return c.json({id,status:"APPROVED",candidate:await r.json()});});
app.post("/v1/intelligence/extractions/:id/reject",async c=>{const x=context(c.req.raw.headers);const{rows}=await pool.query("update candidate_extractions set status='REJECTED',reviewed_by=$3,reviewed_at=now() where tenant_id=$1 and id=$2 and status='REVIEW_REQUIRED' returning *",[x.tenantId,c.req.param("id"),c.req.header("x-actor")||null]);return rows[0]?c.json(rows[0]):c.json({code:"NOT_FOUND",message:"Extraction not found or already reviewed"},404);});
app.post("/v1/intelligence/prompts",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into prompt_versions(id,tenant_id,task,version,prompt,active) values($1,$2,$3,$4,$5,$6)",[id,x.tenantId,String(b.task),String(b.version),String(b.prompt),b.active!==false]);return c.json({id},201);});
app.get("/v1/intelligence/prompts",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from prompt_versions where tenant_id=$1 order by task,created_at desc",[x.tenantId])).rows);});
serve({fetch:app.fetch,port:Number(process.env.PORT||4126)});
export{runAdvice};