"use client";import{FormEvent,useEffect,useState}from"react";
export default function CandidatePortal(){const[data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
async function load(){try{const r=await fetch("/api/portal/session",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error||b.message||"No active application session");setData(b);}catch(e:any){setError(e.message);}}
useEffect(()=>{load();},[]);
async function post(path:string,body:any){setBusy(true);setNotice("");const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),b=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setNotice(b.message||b.error||"Action could not be completed.");return false;}setNotice("Saved.");await load();return true;}
async function withdraw(){if(!confirm("Withdraw this application?"))return;setBusy(true);const r=await fetch("/api/portal/withdraw",{method:"POST"}),b=await r.json();setBusy(false);if(!r.ok){setError(b.error||b.message||"Could not withdraw");return;}await load();}
async function privacy(type:string){await post("/api/portal/privacy",{type});}
async function reschedule(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget);await post("/api/portal/interviews/"+id+"/reschedule",{reason:String(f.get("reason")||""),preferredTimes:String(f.get("preferredTimes")||"").split("\n").map(x=>x.trim()).filter(Boolean)});}
async function submitAssessment(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget);await post("/api/portal/assessments/"+id+"/submit",{content:{response:String(f.get("response")||"")},integrity:{candidateAttested:f.get("attest")==="on"}});}
async function extension(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget),raw=String(f.get("requestedDueAt")||"");await post("/api/portal/assessments/"+id+"/extension",{reason:String(f.get("reason")||""),requestedDueAt:raw?new Date(raw).toISOString():undefined});}
async function acceptOffer(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("acceptedTerms")!=="on"){setNotice("You must confirm that you accept the presented offer and contract.");return;}await post("/api/portal/offers/"+id+"/accept",{signerName:String(f.get("signerName")||""),acceptedTerms:true});}
async function declineOffer(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget);if(confirm("Decline this offer?"))await post("/api/portal/offers/"+id+"/decline",{reason:String(f.get("reason")||"")});}
if(error)return <main className="wrap"><h1>My application</h1><div className="card"><p>{error}</p><a className="button" href="/careers">Return to careers</a></div></main>;
if(!data)return <main className="wrap"><h1>My application</h1><p>Loading…</p></main>;
const stage=data.workflow?.stage||"APPLIED";
return <main className="wrap"><h1>My application</h1>{notice&&<p role="status" className="portalNotice">{notice}</p>}<div className="portalGrid"><div className="card"><small>Role</small><h2>{data.job?.title||data.application?.jobId}</h2><p>{data.job?.location}</p></div><div className="card"><small>Status</small><h2>{stage.replaceAll("_"," ")}</h2><p>Applied {new Date(data.application.createdAt).toLocaleDateString("en-GB")}</p></div></div>

{(data.interviews||[]).length>0&&<section className="portalSection"><h2>Interviews</h2>{data.interviews.map((i:any)=><div className="card" key={i.id}><strong>Round {i.round} · {i.status}</strong>{i.starts_at&&<p>{new Date(i.starts_at).toLocaleString("en-GB")}{i.ends_at?" – "+new Date(i.ends_at).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"}):""}</p>}{i.meeting_url&&<p><a href={i.meeting_url}>Joining details</a></p>}{i.reschedule_status==="REQUESTED"?<p>Your reschedule request is awaiting review.</p>:i.status==="SCHEDULED"&&<details><summary>Request a different time</summary><form onSubmit={e=>reschedule(e,i.id)}><label>Reason<textarea name="reason" required/></label><label>Times that work for you<textarea name="preferredTimes" placeholder="One preferred time per line"/></label><button disabled={busy}>Send request</button></form></details>}</div>)}</section>}

{(data.assessments||[]).length>0&&<section className="portalSection"><h2>Assessments</h2>{data.assessments.map((a:any)=><div className="card" key={a.id}><strong>{a.title}</strong><p>{a.instructions}</p>{a.due_at&&<p>Deadline: {new Date(a.due_at).toLocaleString("en-GB")}</p>}<p>Status: {a.status}</p>{["CREATED","EXTENDED"].includes(a.status)&&<><form onSubmit={e=>submitAssessment(e,a.id)}><label>Your submission<textarea name="response" required/></label><label className="check"><input name="attest" type="checkbox" required/> I confirm this submission is my work, except where collaboration or tools are explicitly permitted.</label><button disabled={busy}>Submit assessment</button></form><details><summary>Request an extension</summary><form onSubmit={e=>extension(e,a.id)}><label>Reason<textarea name="reason" required/></label><label>Requested new deadline<input name="requestedDueAt" type="datetime-local"/></label><button disabled={busy}>Request extension</button></form></details></>}{a.feedback_visible_at&&a.candidate_feedback&&<div className="candidateFeedback"><h3>Feedback</h3><p>{a.candidate_feedback}</p></div>}{a.extension_status&&<p>Extension: {a.extension_status}</p>}</div>)}</section>}

{(data.offers||[]).length>0&&<section className="portalSection"><h2>Offer</h2>{data.offers.map((o:any)=><div className="card offerCard" key={o.id}><div className="sectionHead"><div><strong>Offer · {o.status}</strong><p>{o.compensation?.currency||"GBP"} {o.compensation?.salary||o.compensation?.amount||"Compensation recorded"}</p></div>{o.expires_at&&<small>Expires {new Date(o.expires_at).toLocaleString("en-GB")}</small>}</div>{(o.documents||[]).map((d:any)=><details key={d.id} open><summary>{d.title} · version {d.version}</summary><div className="generatedDocument" dangerouslySetInnerHTML={{__html:d.content}}/></details>)}{o.status==="ISSUED"&&<div className="twoCol"><form onSubmit={e=>acceptOffer(e,o.id)}><h3>Accept electronically</h3><label>Full legal name<input name="signerName" required/></label><label className="check"><input name="acceptedTerms" type="checkbox" required/> I have reviewed the offer and contract shown above and agree to these terms.</label><button disabled={busy}>Accept and sign</button></form><form onSubmit={e=>declineOffer(e,o.id)}><h3>Decline offer</h3><label>Reason<textarea name="reason" required/></label><button className="secondary" disabled={busy}>Decline offer</button></form></div>}{o.status==="ACCEPTED"&&<p><strong>Accepted.</strong> Your recruitment team will continue with onboarding.</p>}</div>)}</section>}

<div className="card" style={{marginTop:18}}><h2>Your controls</h2><p>You can withdraw your application or exercise your data rights here.</p>{!["WITHDRAWN","HIRED","REJECTED"].includes(stage)&&<button disabled={busy} onClick={withdraw}>Withdraw application</button>} <button disabled={busy} onClick={()=>privacy("DSAR")}>Request my data</button> <button disabled={busy} onClick={()=>privacy("ANONYMISE")}>Request anonymisation</button><form action="/api/portal/logout" method="post" style={{marginTop:16}}><button type="submit">End this portal session</button></form></div></main>}