"use client";
import{FormEvent,useEffect,useMemo,useState}from"react";

export default function CandidatePortal(){
 const[data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 async function load(){try{setError("");const r=await fetch("/api/portal/session",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error||b.message||"No active application session");setData(b);}catch(e:any){setError(e.message);}}
 useEffect(()=>{load();},[]);
 async function request(path:string,method:string,body?:any){setBusy(true);setNotice("");const r=await fetch(path,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined}),b=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setNotice(b.message||b.error||"Action could not be completed.");return false;}setNotice("Saved.");await load();return true;}
 async function withdraw(){if(confirm("Withdraw this application?"))await request("/api/portal/withdraw","POST");}
 async function privacy(type:string){await request("/api/portal/privacy","POST",{type});}
 async function reschedule(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget);await request("/api/portal/interviews/"+id+"/reschedule","POST",{reason:String(f.get("reason")||""),preferredTimes:String(f.get("preferredTimes")||"").split("\n").map(x=>x.trim()).filter(Boolean)});}
 async function submitAssessment(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget);await request("/api/portal/assessments/"+id+"/submit","POST",{content:{response:String(f.get("response")||"")},integrity:{candidateAttested:f.get("attest")==="on"}});}
 async function extension(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget),raw=String(f.get("requestedDueAt")||"");await request("/api/portal/assessments/"+id+"/extension","POST",{reason:String(f.get("reason")||""),requestedDueAt:raw?new Date(raw).toISOString():undefined});}
 async function acceptOffer(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget);if(f.get("acceptedTerms")!=="on"){setNotice("You must confirm that you accept the presented offer and contract.");return;}await request("/api/portal/offers/"+id+"/accept","POST",{signerName:String(f.get("signerName")||""),acceptedTerms:true});}
 async function declineOffer(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();const f=new FormData(e.currentTarget);if(confirm("Decline this offer?"))await request("/api/portal/offers/"+id+"/decline","POST",{reason:String(f.get("reason")||"")});}
 async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await request("/api/portal/profile","PATCH",{name:f.get("name"),telephone:f.get("telephone"),location:f.get("location"),linkedIn:f.get("linkedIn"),portfolio:f.get("portfolio"),noticePeriod:f.get("noticePeriod"),preferredBusinessAreas:String(f.get("preferredBusinessAreas")||"").split(",").map(x=>x.trim()).filter(Boolean),preferredRoleTypes:String(f.get("preferredRoleTypes")||"").split(",").map(x=>x.trim()).filter(Boolean),skills:String(f.get("skills")||"").split(",").map(x=>x.trim()).filter(Boolean)});}
 async function savePreferences(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await request("/api/portal/preferences","PUT",{locale:f.get("locale"),accessibilityPreferences:{notes:f.get("accessibility")},alternativeApplicationPreferences:{notes:f.get("alternativeRoute")},talentPoolConsent:f.get("talentPoolConsent")==="on",recruitmentMarketingConsent:f.get("marketingConsent")==="on",keepInTouchConsent:f.get("keepInTouchConsent")==="on",communicationPreferences:{email:f.get("emailUpdates")==="on",jobAlerts:f.get("jobAlertUpdates")==="on",keepInTouch:f.get("keepInTouchConsent")==="on"}});}
 async function createAlert(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await request("/api/portal/job-alerts","POST",{query:f.get("query"),location:f.get("location"),department:f.get("department"),frequency:f.get("frequency"),locale:data?.preferences?.locale||"en-GB"}))e.currentTarget.reset();}
 async function feedback(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await request("/api/portal/feedback","POST",{kind:f.get("kind"),rating:Number(f.get("rating")),comments:f.get("comments"),permissionToContact:f.get("permissionToContact")==="on"}))e.currentTarget.reset();}
 const p=data?.preferences||{},candidate=data?.candidate||{},stage=data?.workflow?.stage||"APPLIED";
 const savedIds=useMemo(()=>new Set((data?.savedJobs||[]).map((x:any)=>x.job_id)),[data?.savedJobs]);
 if(error)return <main className="wrap"><h1>My application</h1><div className="card"><p>{error}</p><a className="button" href="/careers">Return to careers</a></div></main>;
 if(!data)return <main className="wrap"><h1>My application</h1><p>Loading…</p></main>;
 return <main className="wrap candidateAccount"><div className="sectionHead"><div><small>CANDIDATE ACCOUNT</small><h1>My Raeburn</h1><p>Manage your application, profile, preferences and future opportunities in one place.</p></div><a className="button secondary" href="/careers/jobs">Explore roles</a></div>{notice&&<p role="status" className="portalNotice">{notice}</p>}
 <div className="portalGrid"><div className="card"><small>Current role</small><h2>{data.job?.title||data.application?.jobId}</h2><p>{data.job?.location}</p></div><div className="card"><small>Status</small><h2>{stage.replaceAll("_"," ")}</h2><p>Applied {new Date(data.application.createdAt).toLocaleDateString("en-GB")}</p></div></div>

 <nav className="accountNav" aria-label="Candidate account sections"><a href="#journey">Journey</a><a href="#profile">Profile</a><a href="#preferences">Preferences</a><a href="#alerts">Alerts</a><a href="#feedback">Feedback</a></nav>

 <section id="journey" className="portalSection"><div className="sectionHead"><div><small>APPLICATION JOURNEY</small><h2>What happens next</h2></div><p className="hint">Your portal reflects the latest structured stage in Raeburn Talent.</p></div>
 {(data.interviews||[]).length>0&&<div><h3>Interviews</h3>{data.interviews.map((i:any)=><div className="card" key={i.id}><strong>Round {i.round} · {i.status}</strong>{i.starts_at&&<p>{new Date(i.starts_at).toLocaleString("en-GB")}{i.ends_at?" – "+new Date(i.ends_at).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"}):""}</p>}{i.meeting_url&&<p><a href={i.meeting_url}>Joining details</a></p>}{i.reschedule_status==="REQUESTED"?<p>Your reschedule request is awaiting review.</p>:i.status==="SCHEDULED"&&<details><summary>Request a different time</summary><form onSubmit={e=>reschedule(e,i.id)}><label>Reason<textarea name="reason" required/></label><label>Times that work for you<textarea name="preferredTimes" placeholder="One preferred time per line"/></label><button disabled={busy}>Send request</button></form></details>}</div>)}</div>}
 {(data.assessments||[]).length>0&&<div><h3>Assessments</h3>{data.assessments.map((a:any)=><div className="card" key={a.id}><strong>{a.title}</strong><p>{a.instructions}</p>{a.due_at&&<p>Deadline: {new Date(a.due_at).toLocaleString("en-GB")}</p>}<p>Status: {a.status}</p>{["CREATED","EXTENDED"].includes(a.status)&&<><form onSubmit={e=>submitAssessment(e,a.id)}><label>Your submission<textarea name="response" required/></label><label className="check"><input name="attest" type="checkbox" required/> I confirm this submission is my work, except where collaboration or tools are explicitly permitted.</label><button disabled={busy}>Submit assessment</button></form><details><summary>Request an extension</summary><form onSubmit={e=>extension(e,a.id)}><label>Reason<textarea name="reason" required/></label><label>Requested new deadline<input name="requestedDueAt" type="datetime-local"/></label><button disabled={busy}>Request extension</button></form></details></>}{a.feedback_visible_at&&a.candidate_feedback&&<div className="candidateFeedback"><h4>Feedback</h4><p>{a.candidate_feedback}</p></div>}</div>)}</div>}
 {(data.offers||[]).length>0&&<div><h3>Offers</h3>{data.offers.map((o:any)=><div className="card offerCard" key={o.id}><div className="sectionHead"><div><strong>Offer · {o.status}</strong><p>{o.compensation?.currency||"GBP"} {o.compensation?.salary||o.compensation?.amount||"Compensation recorded"}</p></div>{o.expires_at&&<small>Expires {new Date(o.expires_at).toLocaleString("en-GB")}</small>}</div>{(o.documents||[]).map((d:any)=><details key={d.id} open><summary>{d.title} · version {d.version}</summary><div className="generatedDocument" dangerouslySetInnerHTML={{__html:d.content}}/></details>)}{o.status==="ISSUED"&&<div className="twoCol"><form onSubmit={e=>acceptOffer(e,o.id)}><h4>Accept electronically</h4><label>Full legal name<input name="signerName" required/></label><label className="check"><input name="acceptedTerms" type="checkbox" required/> I have reviewed the offer and contract shown above and agree to these terms.</label><button disabled={busy}>Accept and sign</button></form><form onSubmit={e=>declineOffer(e,o.id)}><h4>Decline offer</h4><label>Reason<textarea name="reason" required/></label><button className="secondary" disabled={busy}>Decline offer</button></form></div>}{o.status==="ACCEPTED"&&<p><strong>Accepted.</strong> Your recruitment team will continue with onboarding.</p>}</div>)}</div>}
 </section>

 <section id="profile" className="portalSection"><div><small>REUSABLE PROFILE</small><h2>Your profile</h2><p>Keep this current and future applications can reuse it.</p></div><form className="card formGrid" onSubmit={saveProfile}><label>Full name<input name="name" defaultValue={candidate.name||""} required/></label><label>Telephone<input name="telephone" defaultValue={candidate.telephone||""}/></label><label>Location<input name="location" defaultValue={candidate.location||""}/></label><label>LinkedIn<input name="linkedIn" type="url" defaultValue={candidate.linkedIn||""}/></label><label>Portfolio / GitHub<input name="portfolio" type="url" defaultValue={candidate.portfolio||""}/></label><label>Notice period / availability<input name="noticePeriod" defaultValue={candidate.noticePeriod||""}/></label><label className="span2">Skills, comma separated<input name="skills" defaultValue={(candidate.skills||[]).map((x:any)=>typeof x==="string"?x:x.name||x.skill).filter(Boolean).join(", ")}/></label><label>Preferred business areas<input name="preferredBusinessAreas" defaultValue={(candidate.preferredBusinessAreas||[]).join(", ")}/></label><label>Preferred role types<input name="preferredRoleTypes" defaultValue={(candidate.preferredRoleTypes||[]).join(", ")}/></label><button disabled={busy}>Save profile</button></form></section>

 <section id="preferences" className="portalSection"><div><small>CONTROL</small><h2>Accessibility & communication preferences</h2><p>You decide how Raeburn communicates with you and whether your profile can be considered for future roles.</p></div><form className="card formGrid" onSubmit={savePreferences}><label>Language / locale<select name="locale" defaultValue={p.locale||"en-GB"}><option value="en-GB">English (UK)</option><option value="ne-NP">नेपाली / Nepali</option></select></label><label className="span2">Accessibility / reasonable-adjustment preferences<textarea name="accessibility" defaultValue={p.accessibility_preferences?.notes||""}/></label><label className="span2">Alternative application preferences<textarea name="alternativeRoute" defaultValue={p.alternative_application_preferences?.notes||""}/></label><label className="check"><input name="emailUpdates" type="checkbox" defaultChecked={p.communication_preferences?.email!==false}/> Email me about this application</label><label className="check"><input name="jobAlertUpdates" type="checkbox" defaultChecked={p.communication_preferences?.jobAlerts!==false}/> Allow my job alerts</label><label className="check"><input name="talentPoolConsent" type="checkbox" defaultChecked={!!p.talent_pool_consent}/> Consider me for relevant future roles</label><label className="check"><input name="keepInTouchConsent" type="checkbox" defaultChecked={!!p.keep_in_touch_consent}/> Keep in touch with occasional recruitment updates</label><label className="check"><input name="marketingConsent" type="checkbox" defaultChecked={!!p.recruitment_marketing_consent}/> Send consented recruitment marketing</label><button disabled={busy}>Save preferences</button></form></section>

 <section id="alerts" className="portalSection"><div className="sectionHead"><div><small>DISCOVERY</small><h2>Job alerts</h2></div><p>{savedIds.size} saved role{savedIds.size===1?"":"s"} linked to your account.</p></div><form className="card formGrid" onSubmit={createAlert}><label>Keywords<input name="query"/></label><label>Location<input name="location"/></label><label>Team / category<input name="department"/></label><label>Frequency<select name="frequency" defaultValue="INSTANT"><option value="INSTANT">As relevant roles are published</option></select></label><button disabled={busy}>Create alert</button></form>{(data.alerts||[]).map((a:any)=><div className="card alertRow" key={a.id}><div><strong>{a.query||a.department||a.location||"All relevant roles"}</strong><p>{[a.location,a.department,a.frequency].filter(Boolean).join(" · ")}</p></div><button className="secondary" onClick={()=>request("/api/portal/job-alerts/"+a.id,"DELETE")} disabled={busy}>Unsubscribe</button></div>)}</section>

 <section id="feedback" className="portalSection"><div><small>YOUR EXPERIENCE</small><h2>Tell us how recruitment felt</h2><p>Feedback is recorded separately from selection evidence and is used to improve the candidate experience.</p></div><form className="card formGrid" onSubmit={feedback}><label>Part of the journey<select name="kind"><option value="APPLICATION">Application</option><option value="INTERVIEW">Interview</option><option value="ASSESSMENT">Assessment</option><option value="OFFER">Offer</option></select></label><label>Rating<select name="rating" required defaultValue="5"><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Okay</option><option value="2">2 — Poor</option><option value="1">1 — Very poor</option></select></label><label className="span2">Comments<textarea name="comments"/></label><label className="check"><input name="permissionToContact" type="checkbox"/> You may contact me about this feedback.</label><button disabled={busy}>Send feedback</button></form></section>

 <section className="portalSection"><div className="card"><h2>Your controls</h2><p>You can withdraw your application or exercise your data rights here.</p>{!["WITHDRAWN","HIRED","REJECTED"].includes(stage)&&<button disabled={busy} onClick={withdraw}>Withdraw application</button>} <button disabled={busy} onClick={()=>privacy("DSAR")}>Request my data</button> <button disabled={busy} onClick={()=>privacy("ANONYMISE")}>Request anonymisation</button><form action="/api/portal/logout" method="post" style={{marginTop:16}}><button type="submit">End this portal session</button></form></div></section>
 </main>;
}