import{randomUUID}from"node:crypto";import{serve}from"@hono/node-server";import{Hono}from"hono";import{WorkflowStage}from"@raeburn/contracts";import{createEvent,Events}from"@raeburn/events";import{context,health,pool,withTransaction,writeOutbox}from"@raeburn/service-kit";
const app=new Hono(),APPLICATIONS=process.env.APPLICATIONS_URL||"http://localhost:4103";
const allowed:Record<string,string[]>={APPLIED:["SCREENING","REVIEW","REJECTED","WITHDRAWN","ON_HOLD","TALENT_POOL"],SCREENING:["REVIEW","SHORTLIST","REJECTED","WITHDRAWN","ON_HOLD","TALENT_POOL"],REVIEW:["SHORTLIST","INTERVIEW","REJECTED","WITHDRAWN","ON_HOLD","TALENT_POOL"],SHORTLIST:["INTERVIEW","REJECTED","WITHDRAWN","ON_HOLD","TALENT_POOL"],INTERVIEW:["FINAL_INTERVIEW","OFFER","REJECTED","WITHDRAWN","ON_HOLD","TALENT_POOL"],FINAL_INTERVIEW:["OFFER","REJECTED","WITHDRAWN","ON_HOLD","TALENT_POOL"],OFFER:["HIRED","REJECTED","WITHDRAWN","ON_HOLD"],ON_HOLD:["SCREENING","REVIEW","SHORTLIST","INTERVIEW","FINAL_INTERVIEW","OFFER","REJECTED","WITHDRAWN","TALENT_POOL"],TALENT_POOL:["SCREENING","REVIEW","SHORTLIST","REJECTED","WITHDRAWN","ON_HOLD"],HIRED:[],REJECTED:[],WITHDRAWN:[]};
app.get("/health",async c=>c.json(await health("workflow")));
app.get("/v1/workflow/:applicationId",async c=>{const x=context(c.req.raw.headers);const{rows}=await pool.query("select * from application_workflows where tenant_id=$1 and application_id=$2",[x.tenantId,c.req.param("applicationId")]);if(!rows[0])return c.json({code:"NOT_FOUND",message:"Workflow not found"},404);return c.json(rows[0]);});
app.get("/v1/workflow/:applicationId/history",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from stage_history where tenant_id=$1 and application_id=$2 order by occurred_at desc",[x.tenantId,c.req.param("applicationId")])).rows);});
app.patch("/v1/workflow/:applicationId/stage",async c=>{const x=context(c.req.raw.headers),to=WorkflowStage.parse((await c.req.json()).stage),applicationId=c.req.param("applicationId");const current=await pool.query("select stage from application_workflows where tenant_id=$1 and application_id=$2",[x.tenantId,applicationId]);const from=current.rows[0]?.stage||"APPLIED";if(from===to)return c.json({applicationId,fromStage:from,toStage:to});if(!(allowed[from]||[]).includes(to))return c.json({code:"INVALID_TRANSITION",message:"Transition "+from+" → "+to+" is not allowed",allowed:allowed[from]||[]},409);
let application:any=null;if(to==="HIRED"){const r=await fetch(APPLICATIONS+"/v1/applications/"+applicationId,{headers:{"x-tenant-id":x.tenantId,"x-correlation-id":x.correlationId}});if(r.ok)application=await r.json();}
const result=await withTransaction(async client=>{await client.query("insert into application_workflows(application_id,tenant_id,stage) values($1,$2,$3) on conflict(tenant_id,application_id) do update set stage=excluded.stage,updated_at=now()",[applicationId,x.tenantId,to]);await client.query("insert into stage_history(id,tenant_id,application_id,from_stage,to_stage,actor) values($1,$2,$3,$4,$5,$6)",[randomUUID(),x.tenantId,applicationId,from,to,c.req.header("x-actor")||"system"]);await writeOutbox(client,createEvent({eventType:Events.workflowStageChanged,eventVersion:1,producer:"workflow",correlationId:x.correlationId,tenantId:x.tenantId,payload:{applicationId,fromStage:from,toStage:to}}));if(to==="HIRED")await writeOutbox(client,createEvent({eventType:Events.candidateHired,eventVersion:1,producer:"workflow",correlationId:x.correlationId,tenantId:x.tenantId,payload:{applicationId,candidateId:application?.candidateId||null,jobId:application?.jobId||null}}));return{applicationId,fromStage:from,toStage:to};});return c.json(result);});
serve({fetch:app.fetch,port:Number(process.env.PORT||4105)});