import{randomUUID}from"node:crypto";import{serve}from"@hono/node-server";import{Hono}from"hono";import{WorkflowStage}from"@raeburn/contracts";import{canTransition}from"@raeburn/policy";import{createEvent,Events}from"@raeburn/events";import{context,health,pool,withTransaction,writeOutbox,serviceAuthHeaders,installServiceRuntime}from"@raeburn/service-kit";
const app=new Hono();installServiceRuntime(app,"workflow");const APPLICATIONS=process.env.APPLICATIONS_URL||"http://localhost:4103";
const SLA_HOURS:Record<string,number>={APPLIED:24,SCREENING:48,REVIEW:48,SHORTLIST:72,INTERVIEW:120,FINAL_INTERVIEW:72,OFFER:72,ON_HOLD:168,TALENT_POOL:720};
app.get("/health",async c=>c.json(await health("workflow")));
app.get("/v1/workflow/:applicationId/history",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from stage_history where tenant_id=$1 and application_id=$2 order by occurred_at desc",[x.tenantId,c.req.param("applicationId")])).rows);});
app.patch("/v1/workflow/:applicationId/stage",async c=>{
 const x=context(c.req.raw.headers),body=(await c.req.json()) as any,to=WorkflowStage.parse(body.stage),applicationId=c.req.param("applicationId"),actor=c.req.header("x-actor")||"system";
 const current=await pool.query("select stage from application_workflows where tenant_id=$1 and application_id=$2",[x.tenantId,applicationId]),from=current.rows[0]?.stage||"APPLIED";
 if(from===to)return c.json({applicationId,fromStage:from,toStage:to});if(!canTransition(from,to))return c.json({code:"INVALID_TRANSITION",message:"Transition "+from+" → "+to+" is not allowed"},409);
 const evidenceStages=new Set(["REVIEW","SHORTLIST","INTERVIEW","FINAL_INTERVIEW","OFFER"]);
 let reason:any=null,decisionType:string|null=null;
 if(to==="HIRED"||(to==="REJECTED"&&evidenceStages.has(from))){
   decisionType=to==="HIRED"?"HIRE":"REJECT";
   if(!body.reasonCode||!String(body.rationale||"").trim()||!Array.isArray(body.evidence)||body.evidence.length===0)return c.json({code:"DECISION_EVIDENCE_REQUIRED",message:decisionType==="HIRE"?"Final hiring decisions require a configured reason, rationale and supporting job-related evidence.":"Later-stage rejection requires a configured reason, rationale and supporting job-related evidence."},422);
   reason=(await pool.query("select * from decision_reason_taxonomy where tenant_id=$1 and code=$2 and decision_type=$3 and active=true",[x.tenantId,String(body.reasonCode),decisionType])).rows[0];
   if(!reason)return c.json({code:"INVALID_DECISION_REASON",message:"Select an active "+decisionType.toLowerCase()+" reason from the configured taxonomy."},422);
   const stages=Array.isArray(reason.stages)?reason.stages:[];if(stages.length&&!stages.includes(from))return c.json({code:"REASON_NOT_ALLOWED_FOR_STAGE",message:"This decision reason is not configured for the current stage."},422);
 }
 let application:any=null;if(to==="HIRED"){const r=await fetch(APPLICATIONS+"/v1/applications/"+applicationId,{headers:serviceAuthHeaders({"x-tenant-id":x.tenantId,"x-correlation-id":x.correlationId})});if(r.ok)application=await r.json();}
 const result=await withTransaction(async client=>{
  await client.query("insert into application_workflows(application_id,tenant_id,stage) values($1,$2,$3) on conflict(tenant_id,application_id) do update set stage=excluded.stage,updated_at=now()",[applicationId,x.tenantId,to]);
  await client.query("insert into stage_history(id,tenant_id,application_id,from_stage,to_stage,actor) values($1,$2,$3,$4,$5,$6)",[randomUUID(),x.tenantId,applicationId,from,to,actor]);
  if(reason)await client.query("insert into decision_evidence(id,tenant_id,application_id,from_stage,to_stage,reason_code,rationale,evidence,actor) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9)",[randomUUID(),x.tenantId,applicationId,from,to,reason.code,String(body.rationale).trim(),JSON.stringify(body.evidence),actor]);
  if(SLA_HOURS[to])await client.query("insert into application_slas(tenant_id,application_id,stage,due_at,breached_at) values($1,$2,$3,now()+make_interval(hours=>$4),null) on conflict(tenant_id,application_id,stage) do update set due_at=excluded.due_at,breached_at=null",[x.tenantId,applicationId,to,SLA_HOURS[to]]);
  await writeOutbox(client,createEvent({eventType:Events.workflowStageChanged,eventVersion:1,producer:"workflow",correlationId:x.correlationId,tenantId:x.tenantId,payload:{applicationId,fromStage:from,toStage:to,decisionReasonCode:reason?.code||null,hasDecisionEvidence:Boolean(reason)}}));
  if(to==="HIRED")await writeOutbox(client,createEvent({eventType:Events.candidateHired,eventVersion:1,producer:"workflow",correlationId:x.correlationId,tenantId:x.tenantId,payload:{applicationId,candidateId:application?.candidateId||null,jobId:application?.jobId||null}}));
  return{applicationId,fromStage:from,toStage:to,decisionEvidenceRecorded:Boolean(reason)};
 });return c.json(result);
});
app.get("/v1/workflow/attention/queue",async c=>{const x=context(c.req.raw.headers),userId=c.req.query("userId")||c.req.header("x-actor")||null;const tasks=(await pool.query("select * from workflow_tasks where tenant_id=$1 and status='OPEN' and ($2::text is null or assignee_id=$2) order by case priority when 'URGENT' then 0 when 'HIGH' then 1 else 2 end,due_at nulls last,created_at",[x.tenantId,userId])).rows;const slas=(await pool.query("select * from application_slas where tenant_id=$1 and breached_at is null and due_at<=now()+interval '48 hours' order by due_at",[x.tenantId])).rows;return c.json({tasks,slas});});
app.get("/v1/workflow/:applicationId/notes",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from workflow_notes where tenant_id=$1 and application_id=$2 order by pinned desc,created_at desc",[x.tenantId,c.req.param("applicationId")])).rows);});
app.post("/v1/workflow/:applicationId/notes",async c=>{const x=context(c.req.raw.headers),applicationId=c.req.param("applicationId"),b=(await c.req.json()) as any,id=randomUUID(),body=String(b.body||"").trim();if(!body)return c.json({code:"INVALID_NOTE",message:"Note body is required"},400);const mentions=Array.isArray(b.mentions)?b.mentions:[];await pool.query("insert into workflow_notes(id,tenant_id,application_id,author_id,body,pinned,mentions) values($1,$2,$3,$4,$5,$6,$7::jsonb)",[id,x.tenantId,applicationId,c.req.header("x-actor")||null,body,!!b.pinned,JSON.stringify(mentions)]);return c.json({id,applicationId,body,pinned:!!b.pinned,mentions},201);});
app.patch("/v1/workflow/notes/:id",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any;const{rows}=await pool.query("update workflow_notes set body=coalesce($3,body),pinned=coalesce($4,pinned),updated_at=now() where tenant_id=$1 and id=$2 returning *",[x.tenantId,c.req.param("id"),b.body??null,b.pinned??null]);return rows[0]?c.json(rows[0]):c.json({code:"NOT_FOUND",message:"Note not found"},404);});
app.get("/v1/workflow/tasks",async c=>{const x=context(c.req.raw.headers),status=c.req.query("status"),assignee=c.req.query("assigneeId"),values:any[]=[x.tenantId];let sql="select * from workflow_tasks where tenant_id=$1";if(status){values.push(status);sql+=" and status=$"+values.length;}if(assignee){values.push(assignee);sql+=" and assignee_id=$"+values.length;}sql+=" order by due_at nulls last,created_at desc limit 500";return c.json((await pool.query(sql,values)).rows);});
app.post("/v1/workflow/tasks",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();if(!b.title)return c.json({code:"INVALID_TASK",message:"Task title is required"},400);await pool.query("insert into workflow_tasks(id,tenant_id,application_id,job_id,candidate_id,title,description,assignee_id,status,priority,due_at,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,'OPEN',$9,$10,$11)",[id,x.tenantId,b.applicationId||null,b.jobId||null,b.candidateId||null,String(b.title),b.description||null,b.assigneeId||null,b.priority||"NORMAL",b.dueAt||null,c.req.header("x-actor")||null]);return c.json({id,status:"OPEN"},201);});
app.patch("/v1/workflow/tasks/:id",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any;const status=b.status||null,completed=status==="COMPLETED"?new Date().toISOString():null;const{rows}=await pool.query("update workflow_tasks set title=coalesce($3,title),description=coalesce($4,description),assignee_id=coalesce($5,assignee_id),status=coalesce($6,status),priority=coalesce($7,priority),due_at=coalesce($8,due_at),completed_at=case when $6='COMPLETED' then coalesce(completed_at,now()) when $6 is not null and $6<>'COMPLETED' then null else completed_at end,updated_at=now() where tenant_id=$1 and id=$2 returning *",[x.tenantId,c.req.param("id"),b.title??null,b.description??null,b.assigneeId??null,status,b.priority??null,b.dueAt??null]);return rows[0]?c.json(rows[0]):c.json({code:"NOT_FOUND",message:"Task not found"},404);});
app.get("/v1/workflow/saved-views",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"";return c.json((await pool.query("select * from saved_views where tenant_id=$1 and user_id=$2 order by is_default desc,name",[x.tenantId,userId])).rows);});
app.post("/v1/workflow/saved-views",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"",b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into saved_views(id,tenant_id,user_id,name,resource_type,filters,sort,is_default) values($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8)",[id,x.tenantId,userId,b.name,b.resourceType,JSON.stringify(b.filters||{}),JSON.stringify(b.sort||{}),!!b.isDefault]);return c.json({id},201);});
app.post("/v1/workflow/favourites/:resourceType/:resourceId",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"";await pool.query("insert into favourites(tenant_id,user_id,resource_type,resource_id) values($1,$2,$3,$4) on conflict do nothing",[x.tenantId,userId,c.req.param("resourceType"),c.req.param("resourceId")]);return c.json({ok:true},201);});
app.delete("/v1/workflow/favourites/:resourceType/:resourceId",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"";await pool.query("delete from favourites where tenant_id=$1 and user_id=$2 and resource_type=$3 and resource_id=$4",[x.tenantId,userId,c.req.param("resourceType"),c.req.param("resourceId")]);return c.json({ok:true});});
app.get("/v1/workflow/favourites",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"";return c.json((await pool.query("select * from favourites where tenant_id=$1 and user_id=$2 order by created_at desc",[x.tenantId,userId])).rows);});
app.get("/v1/workflow/recent",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"";return c.json((await pool.query("select * from recent_views where tenant_id=$1 and user_id=$2 order by viewed_at desc limit 20",[x.tenantId,userId])).rows);});
app.post("/v1/workflow/recent",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"",b=(await c.req.json()) as any;if(!b.resourceType||!b.resourceId)return c.json({code:"INVALID_RECENT",message:"resourceType and resourceId are required"},400);await pool.query("insert into recent_views(tenant_id,user_id,resource_type,resource_id,title,href) values($1,$2,$3,$4,$5,$6) on conflict(tenant_id,user_id,resource_type,resource_id) do update set title=excluded.title,href=excluded.href,viewed_at=now()",[x.tenantId,userId,String(b.resourceType),String(b.resourceId),b.title||null,b.href||null]);return c.json({ok:true},201);});
app.get("/v1/workflow/preferences",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"";const row=(await pool.query("select preferences from user_preferences where tenant_id=$1 and user_id=$2",[x.tenantId,userId])).rows[0];return c.json(row?.preferences||{});});
app.put("/v1/workflow/preferences",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"",b=(await c.req.json()) as any;await pool.query("insert into user_preferences(tenant_id,user_id,preferences) values($1,$2,$3::jsonb) on conflict(tenant_id,user_id) do update set preferences=excluded.preferences,updated_at=now()",[x.tenantId,userId,JSON.stringify(b||{})]);return c.json(b||{});});
app.get("/v1/workflow/dashboard-widgets",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"";return c.json((await pool.query("select * from dashboard_widgets where tenant_id=$1 and user_id=$2 order by position,widget_key",[x.tenantId,userId])).rows);});
app.put("/v1/workflow/dashboard-widgets/:key",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"",b=(await c.req.json()) as any;await pool.query("insert into dashboard_widgets(tenant_id,user_id,widget_key,enabled,position,config) values($1,$2,$3,$4,$5,$6::jsonb) on conflict(tenant_id,user_id,widget_key) do update set enabled=excluded.enabled,position=excluded.position,config=excluded.config,updated_at=now()",[x.tenantId,userId,c.req.param("key"),b.enabled!==false,Number(b.position||0),JSON.stringify(b.config||{})]);return c.json({key:c.req.param("key"),enabled:b.enabled!==false,position:Number(b.position||0),config:b.config||{}});});
app.get("/v1/workflow/:applicationId/decisions",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from decision_summaries where tenant_id=$1 and application_id=$2 order by created_at desc",[x.tenantId,c.req.param("applicationId")])).rows);});
app.post("/v1/workflow/:applicationId/decisions",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();if(!b.decision||!b.summary)return c.json({code:"INVALID_DECISION",message:"decision and summary are required"},400);await pool.query("insert into decision_summaries(id,tenant_id,application_id,decision,summary,evidence,created_by) values($1,$2,$3,$4,$5,$6::jsonb,$7)",[id,x.tenantId,c.req.param("applicationId"),String(b.decision),String(b.summary),JSON.stringify(b.evidence||[]),c.req.header("x-actor")||null]);return c.json({id,...b},201);});
app.get("/v1/workflow/automation/rules",async c=>{const x=context(c.req.raw.headers);const[followUps,escalations]=await Promise.all([pool.query("select * from follow_up_rules where tenant_id=$1 order by created_at",[x.tenantId]),pool.query("select * from escalation_rules where tenant_id=$1 order by created_at",[x.tenantId])]);return c.json({followUps:followUps.rows,escalations:escalations.rows});});
app.post("/v1/workflow/automation/follow-up-rules",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into follow_up_rules(id,tenant_id,name,stage,after_hours,title_template,priority,enabled) values($1,$2,$3,$4,$5,$6,$7,$8)",[id,x.tenantId,String(b.name),b.stage||null,Number(b.afterHours||24),String(b.titleTemplate||"Follow up application"),b.priority||"NORMAL",b.enabled!==false]);return c.json({id},201);});
app.post("/v1/workflow/automation/escalation-rules",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into escalation_rules(id,tenant_id,name,stage,after_hours,priority,enabled) values($1,$2,$3,$4,$5,$6,$7)",[id,x.tenantId,String(b.name),b.stage||null,Number(b.afterHours||48),b.priority||"HIGH",b.enabled!==false]);return c.json({id},201);});
app.post("/v1/workflow/:applicationId/notes/:noteId/replies",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID(),body=String(b.body||"").trim();if(!body)return c.json({code:"INVALID_NOTE",message:"Reply body is required"},400);const parent=(await pool.query("select 1 from workflow_notes where tenant_id=$1 and application_id=$2 and id=$3",[x.tenantId,c.req.param("applicationId"),c.req.param("noteId")])).rowCount;if(!parent)return c.json({code:"NOT_FOUND",message:"Parent note not found"},404);await pool.query("insert into workflow_notes(id,tenant_id,application_id,author_id,body,pinned,mentions,parent_note_id,note_type) values($1,$2,$3,$4,$5,false,$6::jsonb,$7,'COMMENT')",[id,x.tenantId,c.req.param("applicationId"),c.req.header("x-actor")||null,body,JSON.stringify(b.mentions||[]),c.req.param("noteId")]);return c.json({id,parentNoteId:c.req.param("noteId"),body},201);});

app.get("/v1/workflow/templates",async c=>{const x=context(c.req.raw.headers),includeInactive=c.req.query("includeInactive")==="true";return c.json((await pool.query("select * from workflow_templates where tenant_id=$1 and ($2::boolean or active=true) order by name",[x.tenantId,includeInactive])).rows);});
app.post("/v1/workflow/templates",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json())as any,id=randomUUID();const{rows}=await pool.query("insert into workflow_templates(id,tenant_id,key,name,stages,rules,active,version,updated_by) values($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7,1,$8) on conflict(tenant_id,key) do update set name=excluded.name,stages=excluded.stages,rules=excluded.rules,active=excluded.active,version=workflow_templates.version+1,updated_by=excluded.updated_by,updated_at=now() returning *",[id,x.tenantId,String(b.key).toUpperCase(),String(b.name),JSON.stringify(b.stages||[]),JSON.stringify(b.rules||{}),b.active!==false,c.req.header("x-actor")||null]);return c.json(rows[0],201);});
app.patch("/v1/workflow/templates/:key",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json())as any;const{rows}=await pool.query("update workflow_templates set name=coalesce($3,name),stages=coalesce($4::jsonb,stages),rules=coalesce($5::jsonb,rules),active=coalesce($6,active),version=version+1,updated_by=$7,updated_at=now() where tenant_id=$1 and key=$2 returning *",[x.tenantId,c.req.param("key").toUpperCase(),b.name??null,b.stages?JSON.stringify(b.stages):null,b.rules?JSON.stringify(b.rules):null,b.active??null,c.req.header("x-actor")||null]);return rows[0]?c.json(rows[0]):c.json({code:"NOT_FOUND",message:"Workflow template not found"},404);});
app.get("/v1/workflow/decision-reasons",async c=>{const x=context(c.req.raw.headers),type=c.req.query("type"),includeInactive=c.req.query("includeInactive")==="true";const vals:any[]=[x.tenantId,includeInactive];let q="select * from decision_reason_taxonomy where tenant_id=$1 and ($2::boolean or active=true)";if(type){vals.push(type.toUpperCase());q+=" and decision_type=$3";}q+=" order by decision_type,label";return c.json((await pool.query(q,vals)).rows);});
app.post("/v1/workflow/decision-reasons",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json())as any,id=randomUUID();await pool.query("insert into decision_reason_taxonomy(id,tenant_id,code,label,decision_type,stages,requires_evidence,guidance) values($1,$2,$3,$4,$5,$6::jsonb,$7,$8) on conflict(tenant_id,code) do update set label=excluded.label,decision_type=excluded.decision_type,stages=excluded.stages,requires_evidence=excluded.requires_evidence,guidance=excluded.guidance,active=true,updated_at=now()",[id,x.tenantId,String(b.code).toUpperCase(),String(b.label),String(b.decisionType||"REJECT").toUpperCase(),JSON.stringify(b.stages||[]),b.requiresEvidence!==false,b.guidance||null]);return c.json({id},201);});
app.patch("/v1/workflow/decision-reasons/:code",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json())as any;const{rows}=await pool.query("update decision_reason_taxonomy set label=coalesce($3,label),stages=coalesce($4::jsonb,stages),requires_evidence=coalesce($5,requires_evidence),guidance=case when $6::text is null then guidance else $6 end,active=coalesce($7,active),updated_at=now() where tenant_id=$1 and code=$2 returning *",[x.tenantId,c.req.param("code").toUpperCase(),b.label??null,b.stages?JSON.stringify(b.stages):null,b.requiresEvidence??null,b.guidance??null,b.active??null]);return rows[0]?c.json(rows[0]):c.json({code:"NOT_FOUND",message:"Decision reason not found"},404);});
app.get("/v1/workflow/:applicationId/decision-evidence",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from decision_evidence where tenant_id=$1 and application_id=$2 order by created_at desc",[x.tenantId,c.req.param("applicationId")])).rows);});

app.get("/v1/workflow/fairness/blind-review/effective",async c=>{const x=context(c.req.raw.headers),stage=String(c.req.query("stage")||""),jobId=String(c.req.query("jobId")||""),organisationId=String(c.req.query("organisationId")||"");const{rows}=await pool.query("select * from blind_review_policies where tenant_id=$1 and enabled=true and ((scope_type='VACANCY' and scope_id=$2) or (scope_type='ORGANISATION' and scope_id=$3) or (scope_type='TENANT' and scope_id in ($1,'*'))) order by case scope_type when 'VACANCY' then 1 when 'ORGANISATION' then 2 else 3 end",[x.tenantId,jobId,organisationId]);for(const row of rows){const stages=Array.isArray(row.stages)?row.stages:[];if(!stages.length||!stage||stages.includes(stage))return c.json({enabled:true,policyId:row.id,scopeType:row.scope_type,scopeId:row.scope_id,hideFields:row.hide_fields||[],stage});}return c.json({enabled:false,stage});});

app.get("/v1/workflow/fairness/blind-review-policies",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from blind_review_policies where tenant_id=$1 order by scope_type,scope_id",[x.tenantId])).rows);});
app.put("/v1/workflow/fairness/blind-review-policies/:scopeType/:scopeId",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json())as any,id=randomUUID();await pool.query("insert into blind_review_policies(id,tenant_id,scope_type,scope_id,stages,hide_fields,enabled) values($1,$2,$3,$4,$5::jsonb,$6::jsonb,$7) on conflict(tenant_id,scope_type,scope_id) do update set stages=excluded.stages,hide_fields=excluded.hide_fields,enabled=excluded.enabled,updated_at=now()",[id,x.tenantId,c.req.param("scopeType").toUpperCase(),c.req.param("scopeId"),JSON.stringify(b.stages||[]),JSON.stringify(b.hideFields||["name","email","telephone","photo","linkedin"]),!!b.enabled]);return c.json({ok:true});});

app.post("/v1/workflow/fairness/consistency-audits",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json())as any,id=randomUUID(),rows=(await pool.query("select from_stage,to_stage,reason_code,actor,count(*)::int decisions from decision_evidence where tenant_id=$1 and created_at>=coalesce($2::timestamptz,'1970-01-01'::timestamptz) and created_at<=coalesce($3::timestamptz,now()) group by from_stage,to_stage,reason_code,actor order by decisions desc",[x.tenantId,b.periodStart||null,b.periodEnd||null])).rows,findings={decisionPatterns:rows,notice:"This consistency report surfaces patterns for human review; it does not infer discrimination or determine whether a decision was lawful."};await pool.query("insert into consistency_audits(id,tenant_id,scope,period_start,period_end,findings) values($1,$2,$3::jsonb,$4,$5,$6::jsonb)",[id,x.tenantId,JSON.stringify(b.scope||{}),b.periodStart||null,b.periodEnd||null,JSON.stringify(findings)]);return c.json({id,findings},201);});
app.get("/v1/workflow/fairness/consistency-audits",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from consistency_audits where tenant_id=$1 order by created_at desc",[x.tenantId])).rows);});

app.post("/v1/workflow/fairness/monitor",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json())as any,id=randomUUID(),min=Math.max(5,Number(b.minimumGroupSize||5)),cohorts=Array.isArray(b.cohorts)?b.cohorts:[];if(cohorts.some((g:any)=>Number(g.size||0)<min))return c.json({code:"GROUP_TOO_SMALL",message:"Fairness monitoring only accepts aggregated cohorts meeting the minimum group size."},422);const rates=cohorts.map((g:any)=>({label:String(g.label),size:Number(g.size),outcomes:Number(g.outcomes||0),rate:Number(g.size)?Number(g.outcomes||0)/Number(g.size):0})),max=Math.max(0,...rates.map((g:any)=>g.rate)),minRate=Math.min(...rates.map((g:any)=>g.rate)),findings={rates,absoluteRateRange:max-minRate,requiresHumanReview:max-minRate>Number(b.reviewThreshold||0.1),notice:"Observed differences are monitoring signals only, not findings of bias or unlawful discrimination."};await pool.query("insert into fairness_monitor_runs(id,tenant_id,metric,cohorts,minimum_group_size,findings,methodology,created_by) values($1,$2,$3,$4::jsonb,$5,$6::jsonb,$7,$8)",[id,x.tenantId,String(b.metric||"selection_rate"),JSON.stringify(cohorts),min,JSON.stringify(findings),String(b.methodology||"Aggregated cohort outcome-rate comparison"),c.req.header("x-actor")||null]);return c.json({id,findings},201);});
app.get("/v1/workflow/fairness/monitor",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from fairness_monitor_runs where tenant_id=$1 order by created_at desc limit 100",[x.tenantId])).rows);});

app.get("/v1/workflow/:applicationId",async c=>{const x=context(c.req.raw.headers);const{rows}=await pool.query("select * from application_workflows where tenant_id=$1 and application_id=$2",[x.tenantId,c.req.param("applicationId")]);if(!rows[0])return c.json({code:"NOT_FOUND",message:"Workflow not found"},404);return c.json(rows[0]);});
serve({fetch:app.fetch,port:Number(process.env.PORT||4105)});