import{randomUUID}from"node:crypto";import type{DomainEvent}from"@raeburn/events";import{createEvent,Events}from"@raeburn/events";import{consumeDurable,pool,withTransaction,withWorkerLease,writeOutbox}from"@raeburn/service-kit";
const SLA_HOURS:Record<string,number>={APPLIED:24,SCREENING:48,REVIEW:48,SHORTLIST:72,INTERVIEW:120,FINAL_INTERVIEW:72,OFFER:72,ON_HOLD:168,TALENT_POOL:720};
async function setStage(e:DomainEvent,applicationId:string,to:string,allowedFrom:string[]){await withTransaction(async client=>{if((await client.query("select 1 from processed_events where event_id=$1",[e.eventId])).rowCount)return;const current=await client.query("select stage from application_workflows where tenant_id=$1 and application_id=$2 for update",[e.tenantId,applicationId]);const from=current.rows[0]?.stage||"APPLIED";if(!current.rows[0])await client.query("insert into application_workflows(application_id,tenant_id,stage) values($1,$2,'APPLIED') on conflict do nothing",[applicationId,e.tenantId]);if(from!==to&&allowedFrom.includes(from)){await client.query("update application_workflows set stage=$3,updated_at=now() where tenant_id=$1 and application_id=$2",[e.tenantId,applicationId,to]);await client.query("insert into stage_history(id,tenant_id,application_id,from_stage,to_stage,actor) values($1,$2,$3,$4,$5,'system:event')",[randomUUID(),e.tenantId,applicationId,from,to]);if(SLA_HOURS[to])await client.query("insert into application_slas(tenant_id,application_id,stage,due_at,breached_at) values($1,$2,$3,now()+make_interval(hours=>$4),null) on conflict(tenant_id,application_id,stage) do update set due_at=excluded.due_at,breached_at=null",[e.tenantId,applicationId,to,SLA_HOURS[to]]);await writeOutbox(client,createEvent({eventType:Events.workflowStageChanged,eventVersion:1,producer:"workflow",correlationId:e.correlationId,causationId:e.eventId,tenantId:e.tenantId,payload:{applicationId,fromStage:from,toStage:to,trigger:e.eventType}}));}await client.query("insert into processed_events(event_id) values($1) on conflict do nothing",[e.eventId]);});}
async function consume(subject:string){await consumeDurable(subject,"workflow-"+subject,async(e:DomainEvent)=>{const p:any=e.payload||{},applicationId=p.applicationId||p.application_id||p.id;if(subject==="application.created.v1"){await withTransaction(async client=>{if((await client.query("select 1 from processed_events where event_id=$1",[e.eventId])).rowCount)return;await client.query("insert into application_workflows(application_id,tenant_id,stage) values($1,$2,'APPLIED') on conflict do nothing",[p.id,e.tenantId]);await client.query("insert into application_slas(tenant_id,application_id,stage,due_at,breached_at) values($1,$2,'APPLIED',now()+interval '24 hours',null) on conflict(tenant_id,application_id,stage) do nothing",[e.tenantId,p.id]);await client.query("insert into processed_events(event_id) values($1) on conflict do nothing",[e.eventId]);});return;}if(!applicationId)return;if(subject==="interview.requested.v1")await setStage(e,applicationId,"INTERVIEW",["APPLIED","SCREENING","REVIEW","SHORTLIST","ON_HOLD"]);if(subject==="interview.scheduled.v1")await setStage(e,applicationId,"INTERVIEW",["APPLIED","SCREENING","REVIEW","SHORTLIST","ON_HOLD"]);if(subject==="offer.created.v1"||subject==="offer.issued.v1")await setStage(e,applicationId,"OFFER",["INTERVIEW","FINAL_INTERVIEW","ON_HOLD"]);});}
for(const subject of["application.created.v1","interview.requested.v1","interview.scheduled.v1","offer.created.v1","offer.issued.v1"])void consume(subject);
const terminalStages=new Set(["HIRED","REJECTED","WITHDRAWN"]);
async function automationTick(){
 const tenants=(await pool.query("select distinct tenant_id from application_workflows")).rows.map((r:any)=>r.tenant_id);
 for(const tenantId of tenants){
  const rules=(await pool.query("select * from follow_up_rules where tenant_id=$1 and enabled=true",[tenantId])).rows;
  const escalationRules=(await pool.query("select * from escalation_rules where tenant_id=$1 and enabled=true",[tenantId])).rows;
  const workflows=(await pool.query("select * from application_workflows where tenant_id=$1",[tenantId])).rows;
  for(const w of workflows){
   if(terminalStages.has(w.stage))continue;
   const ageHours=(Date.now()-new Date(w.updated_at).getTime())/3600000;
   const applicable=rules.length?rules.filter((r:any)=>!r.stage||r.stage===w.stage):[{id:"default-follow-up",after_hours:48,title_template:"Follow up stalled application",priority:"NORMAL"}];
   for(const r of applicable){if(ageHours<Number(r.after_hours))continue;const run=await pool.query("insert into workflow_automation_runs(id,tenant_id,rule_type,rule_id,application_id,result) values($1,$2,'FOLLOW_UP',$3,$4,'TASK_CREATED') on conflict(tenant_id,rule_type,rule_id,application_id) do nothing returning id",[randomUUID(),tenantId,r.id,w.application_id]);if(run.rowCount)await pool.query("insert into workflow_tasks(id,tenant_id,application_id,title,description,status,priority,due_at,created_by) values($1,$2,$3,$4,$5,'OPEN',$6,now(),'system:follow-up')",[randomUUID(),tenantId,w.application_id,r.title_template||"Follow up stalled application","Application has remained in "+w.stage+" for "+Math.floor(ageHours)+" hours.",r.priority||"NORMAL"]);}
   const escalations=escalationRules.length?escalationRules.filter((r:any)=>!r.stage||r.stage===w.stage):[{id:"default-escalation",after_hours:72,priority:"HIGH"}];
   for(const r of escalations){if(ageHours<Number(r.after_hours))continue;const run=await pool.query("insert into workflow_automation_runs(id,tenant_id,rule_type,rule_id,application_id,result) values($1,$2,'ESCALATION',$3,$4,'TASK_CREATED') on conflict(tenant_id,rule_type,rule_id,application_id) do nothing returning id",[randomUUID(),tenantId,r.id,w.application_id]);if(run.rowCount)await pool.query("insert into workflow_tasks(id,tenant_id,application_id,title,description,status,priority,due_at,created_by) values($1,$2,$3,'Escalation: stalled application',$4,'OPEN',$5,now(),'system:escalation')",[randomUUID(),tenantId,w.application_id,"Application has remained in "+w.stage+" for "+Math.floor(ageHours)+" hours.",r.priority||"HIGH"]);}
  }
  const slas=(await pool.query("select * from application_slas where tenant_id=$1 and breached_at is null and due_at<=now()",[tenantId])).rows;
  for(const s of slas){await pool.query("update application_slas set breached_at=now() where tenant_id=$1 and application_id=$2 and stage=$3 and breached_at is null",[tenantId,s.application_id,s.stage]);await pool.query("insert into workflow_tasks(id,tenant_id,application_id,title,description,status,priority,due_at,created_by) values($1,$2,$3,$4,$5,'OPEN','URGENT',now(),'system:sla')",[randomUUID(),tenantId,s.application_id,"SLA breached: "+s.stage,"Application passed its SLA deadline for "+s.stage+"."]);}
 }
}
const automationRun=()=>withWorkerLease("workflow-automation",automationTick).catch(console.error);setInterval(automationRun,60000);void automationRun();
