import{randomUUID}from"node:crypto";
import{serve}from"@hono/node-server";
import{Hono}from"hono";
import{context,health,pool}from"@raeburn/service-kit";

const app=new Hono();
const typedKeys=["skill","employer","title","location","qualification","language","source","recruiter","stage","pool"] as const;
type Filters=Record<string,string|string[]|number|boolean>;

function editDistance(a:string,b:string){const A=a.toLowerCase(),B=b.toLowerCase(),d=Array.from({length:B.length+1},(_,i)=>i);for(let i=1;i<=A.length;i++){let prev=d[0];d[0]=i;for(let j=1;j<=B.length;j++){const tmp=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,prev+(A[i-1]===B[j-1]?0:1));prev=tmp;}}return d[B.length];}
function booleanTsQuery(q:string){const tokens=q.match(/"[^"]+"|\(|\)|\bAND\b|\bOR\b|\bNOT\b|[^\s()]+/gi)||[];const out:string[]=[];for(const raw of tokens){const t=raw.trim();if(/^AND$/i.test(t))out.push("&");else if(/^OR$/i.test(t))out.push("|");else if(/^NOT$/i.test(t))out.push("!");else if(t==="("||t===")")out.push(t);else{const clean=t.replace(/^"|"$/g,"").replace(/[^\p{L}\p{N}_+.#-]+/gu," ").trim().split(/\s+/).filter(Boolean);if(clean.length)out.push(clean.map(x=>x.replace(/[':&|!()]/g,"")).filter(Boolean).join("<->"));}}return out.join(" ").replace(/(?:^|\s)[&|](?=\s|$)/g," ").trim();}
function values(v:any){if(Array.isArray(v))return v.map(String);if(v===undefined||v===null||v==="")return[];return[String(v)];}
function extractFacet(meta:any,key:string){const v=meta?.[key]??meta?.[key+"s"];if(Array.isArray(v))return v.map((x:any)=>typeof x==="string"?x:(x?.name||x?.title||x?.value)).filter(Boolean);if(v&&typeof v==="object")return Object.values(v).filter(x=>typeof x==="string") as string[];return v?[String(v)]:[];}
async function expandTerms(tenantId:string,q:string){const terms=(q.match(/[\p{L}\p{N}+#.\-]+/gu)||[]).filter(t=>!["and","or","not"].includes(t.toLowerCase()));if(!terms.length)return{expanded:q,expansions:[] as any[],suggestions:[] as any[]};const aliases=(await pool.query("select term,canonical_term,kind from search_aliases where tenant_id=$1",[tenantId])).rows;const ontology=(await pool.query("select canonical_name,aliases,related_skills from skill_ontology where tenant_id=$1",[tenantId])).rows;const expansions:any[]=[];const suggestions:any[]=[];let expanded=q;
 for(const term of terms){const low=term.toLowerCase();const exact=aliases.find((a:any)=>String(a.term).toLowerCase()===low);const skill=ontology.find((s:any)=>String(s.canonical_name).toLowerCase()===low||(s.aliases||[]).some((a:any)=>String(a).toLowerCase()===low));const additions=new Set<string>();if(exact)additions.add(exact.canonical_term);if(skill){additions.add(skill.canonical_name);for(const a of skill.aliases||[])additions.add(String(a));for(const r of skill.related_skills||[])additions.add(String(r));}additions.delete(term);if(additions.size){expansions.push({term,expandedTo:[...additions]});expanded+=" OR "+[...additions].map(x=>x.includes(" ")?'"'+x+'"':x).join(" OR ");continue;}const vocab=[...aliases.map((a:any)=>a.term),...aliases.map((a:any)=>a.canonical_term),...ontology.flatMap((s:any)=>[s.canonical_name,...(s.aliases||[])])].map(String);const near=vocab.filter(v=>Math.abs(v.length-term.length)<=2&&editDistance(v,term)<=Math.max(1,Math.floor(term.length/4))).slice(0,3);if(near.length)suggestions.push({term,suggestions:[...new Set(near)]});}
 return{expanded,expansions,suggestions};
}
async function executeSearch(tenantId:string,query:Record<string,string|undefined>){
 const q=(query.q||"").trim(),type=query.type||undefined,limit=Math.min(Math.max(Number(query.limit||100),1),250),semantic=query.semantic==="true"||query.semantic==="1";let filters:Filters={};try{if(query.filters)filters=JSON.parse(query.filters);}catch{}
 for(const key of typedKeys){if(query[key])filters[key]=query[key]!.split(",").map(x=>x.trim()).filter(Boolean);}
 const expansion=semantic?await expandTerms(tenantId,q):{expanded:q,expansions:[],suggestions:[]};const effective=expansion.expanded;const tsq=booleanTsQuery(effective);const valuesSql:any[]=[tenantId];let where="tenant_id=$1";if(type){valuesSql.push(type);where+=" and type=$"+valuesSql.length;}if(tsq){valuesSql.push(tsq);where+=" and search_vector @@ to_tsquery('english',$"+valuesSql.length+")";}
 const rows=(await pool.query("select id,type,title,body,metadata,updated_at from search_documents where "+where+" order by updated_at desc limit 1000",valuesSql)).rows;
 const filtered=rows.filter((r:any)=>Object.entries(filters).every(([k,wanted])=>{const want=values(wanted).map(x=>x.toLowerCase());if(!want.length)return true;const got=extractFacet(r.metadata,k).map(x=>x.toLowerCase());if(k==="skill"||k==="qualification"||k==="language")return want.every(x=>got.some(g=>g.includes(x)||x.includes(g)));return want.some(x=>got.some(g=>g.includes(x)));}));
 const ranked=filtered.map((r:any)=>{let score=1;const hay=(r.title+" "+r.body+" "+JSON.stringify(r.metadata)).toLowerCase();for(const term of (q.match(/[\p{L}\p{N}+#.\-]+/gu)||[])){if(hay.includes(term.toLowerCase()))score+=2;}for(const e of expansion.expansions as any[])for(const term of e.expandedTo)if(hay.includes(String(term).toLowerCase()))score+=.5;return{...r,rank:score};}).sort((a:any,b:any)=>b.rank-a.rank||new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime()).slice(0,limit);
 const facets:Record<string,Record<string,number>>={};for(const key of typedKeys){const counts:Record<string,number>={};for(const r of filtered)for(const v of extractFacet(r.metadata,key)){counts[v]=(counts[v]||0)+1;}facets[key]=Object.fromEntries(Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,30));}
 return{query:q,effectiveQuery:effective,filters,facets,explanation:{mode:semantic?"semantic_expansion":q?"boolean_full_text":"filtered",ranking:"transparent lexical evidence + ontology expansion",booleanQuery:tsq,semanticExpansion:semantic,expansions:expansion.expansions,typoSuggestions:expansion.suggestions,opaqueAiRanking:false},results:ranked};
}
app.get("/health",async c=>c.json(await health("search")));
app.get("/v1/search",async c=>{const x=context(c.req.raw.headers);const query=Object.fromEntries(new URL(c.req.url).searchParams.entries()) as Record<string,string>;return c.json(await executeSearch(x.tenantId,query as any));});
app.post("/v1/search/interpret",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,text=String(b.query||"");const filters:Record<string,string[]>={};const rules:[string,RegExp][]=[["location",/\b(?:in|near)\s+([A-Z][\w -]{2,40})/g],["skill",/\b(?:with|using|skills?\s*(?:in|:))\s+([\w+#., /-]{2,80})/gi],["employer",/\b(?:at|from)\s+([A-Z][\w&. -]{2,60})/g],["language",/\b(?:speaks?|language\s*:?)\s+([A-Za-z -]{2,30})/gi]];for(const[k,re]of rules){for(const m of text.matchAll(re)){filters[k]=[...(filters[k]||[]),...m[1].split(/,|\band\b/i).map(s=>s.trim()).filter(Boolean)];}}const cleaned=text.replace(/\b(?:show|find|search|candidates?|people|applicants?|who|me)\b/gi," ").replace(/\s+/g," ").trim();return c.json({original:text,query:cleaned,filters,inspectable:true,automaticAction:false,explanation:"Rule-based interpretation only; recruiter can edit every generated filter before search."});});
app.get("/v1/search/saved",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"";return c.json((await pool.query("select * from saved_searches where tenant_id=$1 and user_id=$2 order by name",[x.tenantId,userId])).rows);});
app.post("/v1/search/saved",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"",b=(await c.req.json()) as any,id=randomUUID(),interval=Math.max(Number(b.alertIntervalMinutes||1440),60);await pool.query("insert into saved_searches(id,tenant_id,user_id,name,resource_type,query,filters,alert_enabled,next_alert_at,alert_interval_minutes) values($1,$2,$3,$4,$5,$6,$7::jsonb,$8,case when $8 then now() else null end,$9)",[id,x.tenantId,userId,b.name,b.resourceType||null,b.query||"",JSON.stringify(b.filters||{}),!!b.alertEnabled,interval]);return c.json({id},201);});
app.patch("/v1/search/saved/:id",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"",b=(await c.req.json()) as any;const{rows}=await pool.query("update saved_searches set name=coalesce($4,name),query=coalesce($5,query),filters=coalesce($6::jsonb,filters),alert_enabled=coalesce($7,alert_enabled),alert_interval_minutes=coalesce($8,alert_interval_minutes),next_alert_at=case when coalesce($7,alert_enabled) then coalesce(next_alert_at,now()) else null end,updated_at=now() where tenant_id=$1 and user_id=$2 and id=$3 returning *",[x.tenantId,userId,c.req.param("id"),b.name??null,b.query??null,b.filters?JSON.stringify(b.filters):null,b.alertEnabled??null,b.alertIntervalMinutes??null]);return rows[0]?c.json(rows[0]):c.json({code:"NOT_FOUND",message:"Saved search not found"},404);});
app.post("/v1/search/saved/:id/run",async c=>{const x=context(c.req.raw.headers),userId=c.req.header("x-actor")||"",saved=(await pool.query("select * from saved_searches where tenant_id=$1 and user_id=$2 and id=$3",[x.tenantId,userId,c.req.param("id")])).rows[0];if(!saved)return c.json({code:"NOT_FOUND",message:"Saved search not found"},404);const result=await executeSearch(x.tenantId,{q:saved.query,type:saved.resource_type||undefined,filters:JSON.stringify(saved.filters),limit:"250",semantic:"true"});const id=randomUUID(),newCount=Math.max(0,result.results.length-Number(saved.last_result_count||0));await pool.query("insert into search_alert_runs(id,tenant_id,saved_search_id,user_id,result_count,new_result_count,sample_results) values($1,$2,$3,$4,$5,$6,$7::jsonb)",[id,x.tenantId,saved.id,userId,result.results.length,newCount,JSON.stringify(result.results.slice(0,10).map((r:any)=>({id:r.id,type:r.type,title:r.title})))]);await pool.query("update saved_searches set last_alert_at=now(),next_alert_at=now()+(alert_interval_minutes||' minutes')::interval,last_result_count=$4 where tenant_id=$1 and user_id=$2 and id=$3",[x.tenantId,userId,saved.id,result.results.length]);return c.json({runId:id,resultCount:result.results.length,newResultCount:newCount,results:result.results});});
app.get("/v1/search/ontology",async c=>{const x=context(c.req.raw.headers);return c.json({skills:(await pool.query("select * from skill_ontology where tenant_id=$1 order by canonical_name",[x.tenantId])).rows,aliases:(await pool.query("select * from search_aliases where tenant_id=$1 order by term",[x.tenantId])).rows});});
app.post("/v1/search/ontology/skills",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into skill_ontology(id,tenant_id,canonical_name,category,aliases,related_skills) values($1,$2,$3,$4,$5::jsonb,$6::jsonb) on conflict(tenant_id,canonical_name) do update set category=excluded.category,aliases=excluded.aliases,related_skills=excluded.related_skills,updated_at=now()",[id,x.tenantId,b.canonicalName,b.category||null,JSON.stringify(b.aliases||[]),JSON.stringify(b.relatedSkills||[])]);for(const term of b.aliases||[])await pool.query("insert into search_aliases(id,tenant_id,term,canonical_term,kind) values($1,$2,$3,$4,'SKILL_ALIAS') on conflict(tenant_id,term) do update set canonical_term=excluded.canonical_term",[randomUUID(),x.tenantId,term,b.canonicalName]);return c.json({id,canonicalName:b.canonicalName},201);});
app.post("/v1/search/aliases",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into search_aliases(id,tenant_id,term,canonical_term,kind) values($1,$2,$3,$4,$5) on conflict(tenant_id,term) do update set canonical_term=excluded.canonical_term,kind=excluded.kind",[id,x.tenantId,b.term,b.canonicalTerm,b.kind||"ALIAS"]);return c.json({id},201);});
app.get("/v1/search/graph/:type/:id",async c=>{const x=context(c.req.raw.headers);const{rows}=await pool.query("select * from talent_graph_edges where tenant_id=$1 and ((from_type=$2 and from_id=$3) or (to_type=$2 and to_id=$3)) order by weight desc,updated_at desc limit 250",[x.tenantId,c.req.param("type"),c.req.param("id")]);return c.json(rows);});
app.get("/v1/search/similar/candidates/:id",async c=>{const x=context(c.req.raw.headers),id=c.req.param("id"),source=(await pool.query("select * from search_documents where tenant_id=$1 and type='candidate' and id=$2",[x.tenantId,id])).rows[0];if(!source)return c.json([]);const skills=extractFacet(source.metadata,"skill").map(x=>x.toLowerCase()),location=extractFacet(source.metadata,"location")[0]?.toLowerCase();const candidates=(await pool.query("select id,title,metadata,updated_at from search_documents where tenant_id=$1 and type='candidate' and id<>$2 limit 1000",[x.tenantId,id])).rows;const scored=candidates.map((r:any)=>{const other=extractFacet(r.metadata,"skill").map(x=>x.toLowerCase()),shared=skills.filter(s=>other.some(o=>o===s||o.includes(s)||s.includes(o))),loc=location&&extractFacet(r.metadata,"location").some(x=>x.toLowerCase()===location)?1:0;return{...r,similarityEvidence:{sharedSkills:shared,sameLocation:!!loc},score:shared.length*2+loc};}).filter((r:any)=>r.score>0).sort((a:any,b:any)=>b.score-a.score).slice(0,25);return c.json(scored);});
serve({fetch:app.fetch,port:Number(process.env.PORT||4125)});
