import{createHmac}from"node:crypto";import{headers}from"next/headers";
const API=process.env.TALENT_API_URL||"http://localhost:4100",defaultTenant=process.env.TALENT_TENANT_ID||"tenant_raeburn_group";
async function requestHost(){const h=await headers();return(h.get("x-forwarded-host")||h.get("host")||"").split(",")[0].trim().toLowerCase().replace(/:\d+$/,"");}
export async function tenantContext(){const host=await requestHost();if(!host)return{tenantId:defaultTenant,brand:null};try{const r=await fetch(API+"/v1/platform/public/resolve-domain?host="+encodeURIComponent(host),{cache:"no-store"});if(r.ok){const d:any=await r.json();return{tenantId:d.tenant_id||defaultTenant,brand:d.brand||null,name:d.name||null,region:d.region||null};}}catch{}return{tenantId:defaultTenant,brand:null};}
export async function careersRequestHeaders(extra:Record<string,string>={}){const host=await requestHost(),ctx=await tenantContext(),out:Record<string,string>={...extra,"x-tenant-id":ctx.tenantId};const secret=process.env.CAREERS_ROUTING_SECRET;if(secret&&host){const timestamp=String(Date.now()),signature=createHmac("sha256",secret).update(host+"|"+timestamp).digest("base64url");out["x-careers-host"]=host;out["x-careers-timestamp"]=timestamp;out["x-careers-signature"]=signature;}return out;}
export async function jobs(){const r=await fetch(API+"/v1/jobs/public",{headers:await careersRequestHeaders(),cache:"no-store"});if(!r.ok)throw new Error("Jobs unavailable");return r.json();}
export async function jobBySlug(slug:string){const r=await fetch(API+"/v1/jobs/public/"+encodeURIComponent(slug),{headers:await careersRequestHeaders(),cache:"no-store"});if(!r.ok)return null;return r.json();}
export async function jobsForGateway(gateway:string){const rows:any[]=await jobs();if(gateway==="mainstream")return rows;return rows.filter(j=>(j.audiences||[]).includes(gateway));}
export async function campaign(slug:string){const r=await fetch(API+"/v1/campaigns/public/"+encodeURIComponent(slug),{headers:await careersRequestHeaders(),cache:"no-store"});if(!r.ok)return null;return r.json();}
