import{api}from"../../lib/api";
function Count({label,value,detail}:{label:string;value:any;detail?:string}){return <div className="card"><small>{label}</small><h2>{value??0}</h2>{detail&&<p>{detail}</p>}</div>}
export default async function Page(){
 const[security,lawful,lia,processing,subprocessors,dataMap,residency,signoffs,decisions,blindPolicies,consistency,fairness,ai,models,changes,impacts,engagement]=await Promise.all([
  api("/v1/identity/security-events"),api("/v1/privacy/lawful-bases"),api("/v1/privacy/legitimate-interests"),api("/v1/privacy/processing-activities"),api("/v1/privacy/subprocessors"),api("/v1/privacy/data-map"),api("/v1/privacy/data-residency"),api("/v1/privacy/compliance-signoffs"),
  api("/v1/workflow/decision-reasons"),api("/v1/workflow/fairness/blind-review-policies"),api("/v1/workflow/fairness/consistency-audits"),api("/v1/workflow/fairness/monitor"),api("/v1/intelligence/governance/status"),api("/v1/intelligence/governance/models"),api("/v1/intelligence/governance/model-changes"),api("/v1/intelligence/governance/impact-assessments"),api("/v1/organisations/compliance-reviews")
 ]);
 const pendingSignoffs=(signoffs||[]).filter((x:any)=>x.status!=="APPROVED").length,pendingModel=(changes||[]).filter((x:any)=>x.decision==="PENDING").length,openEngagement=(engagement||[]).filter((x:any)=>x.status!=="CLOSED").length;
 return <><div className="pageHeader"><div><h1>Governance & compliance</h1><p>Security, privacy, fair-selection and responsible-AI evidence in one place.</p></div><div className="headerActions"><a className="button" href="/privacy">Privacy requests</a><a className="button secondary" href="/security">Identity security</a></div></div>
 <div className="stats"><Count label="Security events" value={(security||[]).length}/><Count label="Lawful bases" value={(lawful||[]).length}/><Count label="Processing activities" value={(processing||[]).length}/><Count label="Pending sign-offs" value={pendingSignoffs}/><Count label="Pending AI changes" value={pendingModel}/><Count label="Open agency/contractor reviews" value={openEngagement}/></div>
 <div className="twoCol"><section><h2>Privacy governance</h2><div className="card"><p><strong>Lawful-basis records:</strong> {(lawful||[]).length}</p><p><strong>Legitimate-interest assessments:</strong> {(lia||[]).length}</p><p><strong>Subprocessors:</strong> {(subprocessors||[]).length}</p><p><strong>Data-map records:</strong> {(dataMap||[]).length}</p><p><strong>Residency records:</strong> {(residency||[]).length}</p><p><strong>Formal sign-offs:</strong> {(signoffs||[]).length}</p></div></section>
 <section><h2>Responsible AI</h2><div className="card"><p><strong>Approved models:</strong> {ai?.models?.approved||0} / {ai?.models?.total||0}</p><p><strong>Candidate impact assessments:</strong> {ai?.impactAssessments?.approved||0} approved / {ai?.impactAssessments?.total||0}</p><p><strong>Blocked unapproved runs (30d):</strong> {ai?.blockedRunsLast30Days||0}</p><p><strong>Model change reviews:</strong> {(changes||[]).length}</p></div></section></div>
 <div className="twoCol"><section><h2>Selection fairness controls</h2><div className="card"><p><strong>Decision reasons:</strong> {(decisions||[]).length}</p><p><strong>Active blind-review policies:</strong> {(blindPolicies||[]).filter((x:any)=>x.enabled).length}</p><p><strong>Consistency audits:</strong> {(consistency||[]).length}</p><p><strong>Aggregated fairness monitors:</strong> {(fairness||[]).length}</p><p>Final hire and later-stage rejection decisions require a configured reason, written rationale and linked job-related evidence. Active blind-review policy is enforced in candidate review surfaces.</p></div></section>
 <section><h2>Agency & contractor compliance</h2><div className="card"><p><strong>Total reviews:</strong> {(engagement||[]).length}</p><p><strong>Open reviews:</strong> {openEngagement}</p><p>Reviews cover agency-worker responsibilities, contractual terms, employment-status classification and off-payroll/IR35 considerations.</p></div></section></div>
 <h2>Recent security activity</h2><table><thead><tr><th>Time</th><th>Event</th><th>User/email</th><th>Network/device evidence</th></tr></thead><tbody>{(security||[]).slice(0,20).map((e:any)=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString("en-GB")}</td><td>{e.event_type}</td><td>{e.email||e.user_id||"—"}</td><td>{e.ip_hash?"IP hash recorded":"—"} · {e.user_agent_hash?"device hash recorded":"—"}</td></tr>)}</tbody></table>
 <h2>Formal compliance sign-offs</h2><table><thead><tr><th>Area</th><th>Version</th><th>Status</th><th>Reviewer</th><th>Review due</th></tr></thead><tbody>{(signoffs||[]).map((s:any)=><tr key={s.id}><td>{s.area}</td><td>{s.version}</td><td>{s.status}</td><td>{[s.reviewer_name,s.reviewer_role,s.reviewer_organisation].filter(Boolean).join(" · ")||"—"}</td><td>{s.review_due_at?new Date(s.review_due_at).toLocaleDateString("en-GB"):"—"}</td></tr>)}</tbody></table>
 <h2>AI model register</h2><table><thead><tr><th>Provider</th><th>Model</th><th>Version</th><th>Status</th><th>Review due</th></tr></thead><tbody>{(models||[]).map((m:any)=><tr key={m.id}><td>{m.provider}</td><td>{m.model}</td><td>{m.version}</td><td>{m.status}</td><td>{m.review_due_at?new Date(m.review_due_at).toLocaleDateString("en-GB"):"—"}</td></tr>)}</tbody></table>
 </>;
}
