FROM node:22-alpine
WORKDIR /app
COPY . .
RUN npm install --omit=optional
ARG WORKSPACE
ARG SCRIPT=worker
ENV WORKSPACE=$WORKSPACE
ENV SCRIPT=$SCRIPT
ENV NODE_ENV=production
CMD ["sh","-c","npm --workspace "$WORKSPACE" run "$SCRIPT""]
