FROM node:22-alpine
WORKDIR /app
RUN npm install -g npm@12.1.0
COPY . .
RUN npm ci --omit=optional
ARG WORKSPACE
ENV WORKSPACE=$WORKSPACE
ENV NODE_ENV=production
CMD ["sh","-c","npm --workspace "$WORKSPACE" run start"]
