import type{ButtonHTMLAttributes,HTMLAttributes,InputHTMLAttributes,ReactNode,TableHTMLAttributes}from"react";
export function Button({children,className="",...props}:ButtonHTMLAttributes<HTMLButtonElement>){return <button className={"rb-button "+className} {...props}>{children}</button>;}
export function Card({children,className="",...props}:HTMLAttributes<HTMLDivElement>){return <div className={"rb-card "+className} {...props}>{children}</div>;}
export function Badge({children,tone="neutral"}:{children:ReactNode;tone?:"neutral"|"success"|"warning"|"danger"}){return <span className={"rb-badge rb-badge-"+tone}>{children}</span>;}
export function EmptyState({title,body,action}:{title:string;body:string;action?:ReactNode}){return <div className="rb-empty"><h3>{title}</h3><p>{body}</p>{action}</div>;}
export function PageHeader({title,description,actions}:{title:string;description?:string;actions?:ReactNode}){return <div className="rb-page-header"><div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions}</div>;}
export function FormField({label,hint,error,children}:{label:string;hint?:string;error?:string;children:ReactNode}){return <label className="rb-field"><span>{label}</span>{children}{hint&&!error&&<small>{hint}</small>}{error&&<small role="alert" className="rb-field-error">{error}</small>}</label>;}
export function Input(props:InputHTMLAttributes<HTMLInputElement>){return <input className={"rb-input "+(props.className||"")} {...props}/>;}
export function DataTable({children,className="",...props}:TableHTMLAttributes<HTMLTableElement>){return <div className="rb-table-wrap"><table className={"rb-table "+className} {...props}>{children}</table></div>;}
export function Drawer({open,title,onClose,children}:{open:boolean;title:string;onClose?:()=>void;children:ReactNode}){if(!open)return null;return <div className="rb-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.();}}><section className="rb-drawer" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2>{onClose&&<button type="button" onClick={onClose} aria-label="Close">×</button>}</header>{children}</section></div>;}
export function Modal({open,title,onClose,children,footer}:{open:boolean;title:string;onClose?:()=>void;children:ReactNode;footer?:ReactNode}){if(!open)return null;return <div className="rb-overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose?.();}}><section className="rb-modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2>{onClose&&<button type="button" onClick={onClose} aria-label="Close">×</button>}</header><div>{children}</div>{footer&&<footer>{footer}</footer>}</section></div>;}
export function Toast({children,tone="neutral",onDismiss}:{children:ReactNode;tone?:"neutral"|"success"|"warning"|"danger";onDismiss?:()=>void}){return <div className={"rb-toast rb-toast-"+tone} role={tone==="danger"?"alert":"status"}>{children}{onDismiss&&<button type="button" onClick={onDismiss} aria-label="Dismiss notification">×</button>}</div>;}
export function BarChart({data,max,label}:{data:{label:string;value:number}[];max?:number;label?:string}){const ceiling=max||Math.max(1,...data.map(d=>d.value));return <figure className="rb-chart" aria-label={label||"Bar chart"}>{data.map(d=><div className="rb-chart-row" key={d.label}><span>{d.label}</span><div className="rb-chart-track"><span className="rb-chart-bar" style={{width:Math.max(2,Math.min(100,d.value/ceiling*100))+"%"}}/></div><strong>{d.value}</strong></div>)}</figure>;}
