insert into assessment_templates(id,tenant_id,name,type,instructions,rubric,accessibility_options,version) values
('at_technical','tenant_raeburn_group','Technical Work Sample','TECHNICAL','Complete the role-relevant technical exercise. Explain assumptions and trade-offs.','{"dimensions":[{"key":"correctness","label":"Correctness","required":true},{"key":"reasoning","label":"Reasoning","required":true},{"key":"maintainability","label":"Maintainability","required":true},{"key":"communication","label":"Communication","required":true}]}'::jsonb,'{"extensions":true,"alternativeFormat":true}'::jsonb,1),
('at_case','tenant_raeburn_group','Case Study','CASE_STUDY','Review the case and provide a structured recommendation supported by evidence.','{"dimensions":[{"key":"analysis","label":"Analysis","required":true},{"key":"judgement","label":"Judgement","required":true},{"key":"communication","label":"Communication","required":true}]}'::jsonb,'{"extensions":true,"alternativeFormat":true}'::jsonb,1),
('at_presentation','tenant_raeburn_group','Presentation','PRESENTATION','Prepare a concise presentation responding to the supplied brief.','{"dimensions":[{"key":"structure","label":"Structure","required":true},{"key":"evidence","label":"Use of evidence","required":true},{"key":"delivery","label":"Delivery","required":true}]}'::jsonb,'{"extensions":true,"alternativeFormat":true}'::jsonb,1),
('at_writing','tenant_raeburn_group','Writing Exercise','WRITING','Complete the written exercise in a clear, audience-appropriate format.','{"dimensions":[{"key":"clarity","label":"Clarity","required":true},{"key":"accuracy","label":"Accuracy","required":true},{"key":"judgement","label":"Judgement","required":true}]}'::jsonb,'{"extensions":true,"alternativeFormat":true}'::jsonb,1),
('at_sales','tenant_raeburn_group','Commercial / Sales Exercise','SALES','Respond to the commercial scenario and explain your approach.','{"dimensions":[{"key":"discovery","label":"Discovery","required":true},{"key":"commercial","label":"Commercial judgement","required":true},{"key":"communication","label":"Communication","required":true}]}'::jsonb,'{"extensions":true,"alternativeFormat":true}'::jsonb,1),
('at_finance','tenant_raeburn_group','Finance Work Sample','FINANCE','Complete the finance scenario and show your assumptions and checks.','{"dimensions":[{"key":"accuracy","label":"Accuracy","required":true},{"key":"controls","label":"Controls","required":true},{"key":"analysis","label":"Analysis","required":true}]}'::jsonb,'{"extensions":true,"alternativeFormat":true}'::jsonb,1)
on conflict(id) do nothing;

insert into assessment_template_versions(id,tenant_id,template_id,version,snapshot,created_by)
select 'atv_'||id,'tenant_raeburn_group',id,1,jsonb_build_object('name',name,'type',type,'instructions',instructions,'rubric',rubric,'accessibilityOptions',accessibility_options,'version',1),'seed'
from assessment_templates where tenant_id='tenant_raeburn_group'
on conflict(tenant_id,template_id,version) do nothing;