import{createHash,randomUUID}from"node:crypto";
import{serve}from"@hono/node-server";
import{Hono}from"hono";
import{z}from"zod";
import{createEvent,Events}from"@raeburn/events";
import{context,health,pool,withTransaction,writeOutbox}from"@raeburn/service-kit";

const app=new Hono();
const APPLICATIONS=process.env.APPLICATIONS_URL||"http://localhost:4103";
const JOBS=process.env.JOBS_URL||"http://localhost:4101";
const CANDIDATES=process.env.CANDIDATES_URL||"http://localhost:4102";
const sha=(v:string)=>createHash("sha256").update(v).digest("hex");
const headers=(tenantId:string,correlationId:string)=>({"x-tenant-id":tenantId,"x-correlation-id":correlationId});

async function hydrate(tenantId:string,correlationId:string,applicationId:string){
 const h=headers(tenantId,correlationId),aRes=await fetch(APPLICATIONS+"/v1/applications/"+applicationId,{headers:h});if(!aRes.ok)return null;
 const application:any=await aRes.json();
 const[jRes,cRes]=await Promise.all([fetch(JOBS+"/v1/jobs/"+application.jobId,{headers:h}),fetch(CANDIDATES+"/v1/candidates/"+application.candidateId,{headers:h})]);
 return{application,job:jRes.ok?await jRes.json():null,candidate:cRes.ok?await cRes.json():null};
}
async function requiredApprovals(tenantId:string,organisationId?:string|null){
 const{rows}=await pool.query("select approval_type,condition from offer_approval_rules where tenant_id=$1 and active=true and required=true and (organisation_id is null or organisation_id=$2) order by organisation_id nulls first,approval_type",[tenantId,organisationId||null]);
 const configured=[...new Set(rows.map((r:any)=>r.approval_type))];return configured.length?configured:["HIRING_MANAGER","FINANCE"];
}
function amount(comp:any){const raw=comp?.salary??comp?.amount??comp?.baseSalary;const n=Number(raw);return Number.isFinite(n)?n:null;}

app.get("/health",async c=>c.json(await health("offers")));
app.get("/v1/offers",async c=>{const x=context(c.req.raw.headers),applicationId=c.req.query("applicationId");const r=applicationId?await pool.query("select * from offers where tenant_id=$1 and application_id=$2 order by version desc",[x.tenantId,applicationId]):await pool.query("select * from offers where tenant_id=$1 order by created_at desc limit 250",[x.tenantId]);return c.json(r.rows);});

app.post("/v1/offers",async c=>{
 const x=context(c.req.raw.headers),b=z.object({applicationId:z.string(),compensation:z.record(z.string(),z.unknown()).default({}),equity:z.record(z.string(),z.unknown()).default({}),conditions:z.array(z.unknown()).default([]),startDate:z.string().optional(),probation:z.string().optional(),benefits:z.record(z.string(),z.unknown()).default({}),expiresAt:z.string().datetime().optional(),salaryBandId:z.string().optional()}).parse(await c.req.json()),id=randomUUID(),h=await hydrate(x.tenantId,x.correlationId,b.applicationId);
 if(!h?.job)return c.json({code:"APPLICATION_CONTEXT_UNAVAILABLE",message:"Could not resolve vacancy context"},409);
 const approvals=await requiredApprovals(x.tenantId,h.job.hiringOrganisationId);
 const value={id,applicationId:b.applicationId,status:"DRAFT",version:1,compensation:b.compensation,equity:b.equity,conditions:b.conditions,startDate:b.startDate||null,probation:b.probation||null,benefits:b.benefits,expiresAt:b.expiresAt||null,salaryBandId:b.salaryBandId||null,requiredApprovals:approvals};
 await withTransaction(async client=>{await client.query("insert into offers(id,tenant_id,application_id,compensation,equity,conditions,start_date,probation,benefits,expires_at,salary_band_id,required_approvals,updated_by) values($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb,$7,$8,$9::jsonb,$10,$11,$12::jsonb,$13)",[id,x.tenantId,b.applicationId,JSON.stringify(b.compensation),JSON.stringify(b.equity),JSON.stringify(b.conditions),b.startDate||null,b.probation||null,JSON.stringify(b.benefits),b.expiresAt||null,b.salaryBandId||null,JSON.stringify(approvals),c.req.header("x-actor")||null]);await client.query("insert into offer_versions(id,tenant_id,offer_id,version,snapshot,created_by) values($1,$2,$3,1,$4::jsonb,$5)",[randomUUID(),x.tenantId,id,JSON.stringify(value),c.req.header("x-actor")||null]);for(const approvalType of approvals)await client.query("insert into offer_approvals(id,tenant_id,offer_id,approval_type,status) values($1,$2,$3,$4,'PENDING') on conflict(tenant_id,offer_id,approval_type) do nothing",[randomUUID(),x.tenantId,id,approvalType]);await writeOutbox(client,createEvent({eventType:Events.offerCreated,eventVersion:1,producer:"offers",correlationId:x.correlationId,tenantId:x.tenantId,payload:value}));});return c.json(value,201);
});

app.patch("/v1/offers/:id",async c=>{const x=context(c.req.raw.headers),id=c.req.param("id"),b=(await c.req.json()) as any,current=(await pool.query("select * from offers where tenant_id=$1 and id=$2",[x.tenantId,id])).rows[0];if(!current)return c.json({code:"NOT_FOUND",message:"Offer not found"},404);if(current.status!=="DRAFT")return c.json({code:"INVALID_STATE",message:"Only draft offers can be edited"},409);const version=Number(current.version)+1,comp=b.compensation??current.compensation,equity=b.equity??current.equity,conditions=b.conditions??current.conditions,benefits=b.benefits??current.benefits;const{rows}=await pool.query("update offers set version=$3,compensation=$4::jsonb,equity=$5::jsonb,conditions=$6::jsonb,start_date=coalesce($7,start_date),probation=coalesce($8,probation),benefits=$9::jsonb,expires_at=coalesce($10,expires_at),salary_band_id=coalesce($11,salary_band_id),updated_by=$12,updated_at=now() where tenant_id=$1 and id=$2 returning *",[x.tenantId,id,version,JSON.stringify(comp),JSON.stringify(equity),JSON.stringify(conditions),b.startDate??null,b.probation??null,JSON.stringify(benefits),b.expiresAt??null,b.salaryBandId??null,c.req.header("x-actor")||null]);await pool.query("insert into offer_versions(id,tenant_id,offer_id,version,snapshot,created_by) values($1,$2,$3,$4,$5::jsonb,$6)",[randomUUID(),x.tenantId,id,version,JSON.stringify(rows[0]),c.req.header("x-actor")||null]);return c.json(rows[0]);});

app.get("/v1/offers/:id/readiness",async c=>{
 const x=context(c.req.raw.headers),offer=(await pool.query("select * from offers where tenant_id=$1 and id=$2",[x.tenantId,c.req.param("id")])).rows[0];if(!offer)return c.json({code:"NOT_FOUND",message:"Offer not found"},404);
 const h=await hydrate(x.tenantId,x.correlationId,offer.application_id),issues:string[]=[];
 const approvals=(await pool.query("select approval_type,status from offer_approvals where tenant_id=$1 and offer_id=$2",[x.tenantId,offer.id])).rows,approved=new Set(approvals.filter((a:any)=>a.status==="APPROVED").map((a:any)=>a.approval_type));
 for(const a of offer.required_approvals||[])if(!approved.has(a))issues.push("Approval required: "+a);
 const bandsRes=await fetch(JOBS+"/v1/jobs/salary-bands",{headers:headers(x.tenantId,x.correlationId)}),bands:any[]=bandsRes.ok?await bandsRes.json():[],salary=amount(offer.compensation),currency=offer.compensation?.currency||"GBP";
 const matching=offer.salary_band_id?bands.find(b=>b.id===offer.salary_band_id):bands.filter(b=>(!b.organisation_id||b.organisation_id===h?.job?.hiringOrganisationId)&&(!b.department||b.department===h?.job?.department)&&(b.currency||"GBP")===currency)[0];
 if(salary===null)issues.push("Numeric base compensation is required.");
 if(matching&&salary!==null&&(salary<Number(matching.min_amount)||salary>Number(matching.max_amount)))issues.push("Compensation is outside the approved salary band.");
 if(!matching)issues.push("No approved salary band matches this offer.");
 const docs=(await pool.query("select document_type from offer_documents where tenant_id=$1 and offer_id=$2 and status='GENERATED'",[x.tenantId,offer.id])).rows.map((r:any)=>r.document_type);if(!docs.includes("OFFER_LETTER"))issues.push("Offer letter has not been generated.");if(!docs.includes("CONTRACT"))issues.push("Contract has not been generated.");
 return c.json({ready:issues.length===0,issues,approvals,salaryBand:matching||null,job:h?.job||null});
});

app.post("/v1/offers/:id/generate-documents",async c=>{
 const x=context(c.req.raw.headers),offer=(await pool.query("select * from offers where tenant_id=$1 and id=$2",[x.tenantId,c.req.param("id")])).rows[0];if(!offer)return c.json({code:"NOT_FOUND",message:"Offer not found"},404);if(offer.status!=="DRAFT")return c.json({code:"INVALID_STATE",message:"Documents can only be regenerated while an offer is draft"},409);
 const h=await hydrate(x.tenantId,x.correlationId,offer.application_id);if(!h?.job||!h?.candidate)return c.json({code:"CONTEXT_UNAVAILABLE",message:"Could not resolve candidate/job context"},502);
 const candidate=h.candidate.name||"Candidate",job=h.job.title||"Role",salary=amount(offer.compensation),currency=offer.compensation?.currency||"GBP",start=offer.start_date?new Date(offer.start_date).toLocaleDateString("en-GB"):"to be agreed",expiry=offer.expires_at?new Date(offer.expires_at).toLocaleString("en-GB"):"as stated by the recruitment team";
 const offerLetter=`<article><h1>Offer of employment — ${job}</h1><p>Dear ${candidate},</p><p>We are pleased to offer you the position of <strong>${job}</strong> with The Raeburn Group.</p><p>Base compensation: <strong>${currency} ${salary??"as agreed"}</strong>.</p><p>Proposed start date: <strong>${start}</strong>.</p><p>This offer is subject to the conditions recorded in your Raeburn Talent offer and expires ${expiry}.</p><p>Please review the accompanying contract before accepting electronically.</p></article>`;
 const contract=`<article><h1>Employment terms — ${job}</h1><p>Candidate: <strong>${candidate}</strong></p><p>Role: <strong>${job}</strong></p><p>Start date: <strong>${start}</strong></p><p>Base compensation: <strong>${currency} ${salary??"as agreed"}</strong></p><p>Probation: <strong>${offer.probation||"As agreed"}</strong></p><h2>Conditions</h2><pre>${JSON.stringify(offer.conditions||[],null,2)}</pre><h2>Benefits</h2><pre>${JSON.stringify(offer.benefits||{},null,2)}</pre><p>Electronic acceptance records agreement to the version of these terms presented in Raeburn Talent.</p></article>`;
 const created=[];for(const[dtype,title,content]of[["OFFER_LETTER","Offer letter",offerLetter],["CONTRACT","Employment contract",contract]] as const){const version=((await pool.query("select coalesce(max(version),0)::int v from offer_documents where tenant_id=$1 and offer_id=$2 and document_type=$3",[x.tenantId,offer.id,dtype])).rows[0]?.v||0)+1,id=randomUUID();await pool.query("insert into offer_documents(id,tenant_id,offer_id,document_type,version,title,content,content_hash,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9)",[id,x.tenantId,offer.id,dtype,version,title,content,sha(content),c.req.header("x-actor")||null]);created.push({id,documentType:dtype,version,title,contentHash:sha(content)});}return c.json({offerId:offer.id,documents:created},201);
});

app.get("/v1/offers/:id/documents",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select id,document_type,version,title,content,content_hash,status,created_at from offer_documents where tenant_id=$1 and offer_id=$2 order by document_type,version desc",[x.tenantId,c.req.param("id")])).rows);});
app.get("/v1/offers/documents/:documentId",async c=>{const x=context(c.req.raw.headers),d=(await pool.query("select * from offer_documents where tenant_id=$1 and id=$2",[x.tenantId,c.req.param("documentId")])).rows[0];return d?c.json(d):c.json({code:"NOT_FOUND",message:"Offer document not found"},404);});

app.post("/v1/offers/:id/issue",async c=>{const x=context(c.req.raw.headers),id=c.req.param("id"),offer=(await pool.query("select * from offers where tenant_id=$1 and id=$2",[x.tenantId,id])).rows[0];if(!offer)return c.json({code:"NOT_FOUND",message:"Offer not found"},404);if(offer.status!=="DRAFT")return c.json({code:"INVALID_STATE",message:"Only draft offers can be issued"},409);
 const readyReq=new Request("http://internal/v1/offers/"+id+"/readiness",{headers:c.req.raw.headers});const readyRes=await app.fetch(readyReq),ready:any=await readyRes.json();if(!ready.ready)return c.json({code:"OFFER_NOT_READY",message:"Offer cannot be issued until all controls pass",issues:ready.issues},409);
 const value=await transition(x,id,"ISSUED",Events.offerIssued,{issued_at:new Date().toISOString()});return c.json(value);
});

app.post("/v1/offers/:id/accept",async c=>{const x=context(c.req.raw.headers),b=z.object({signerName:z.string().min(2),acceptedTerms:z.literal(true)}).parse(await c.req.json()),id=c.req.param("id"),offer=(await pool.query("select * from offers where tenant_id=$1 and id=$2",[x.tenantId,id])).rows[0];if(!offer)return c.json({code:"NOT_FOUND",message:"Offer not found"},404);if(offer.status!=="ISSUED")return c.json({code:"INVALID_STATE",message:"Only issued offers can be accepted"},409);if(offer.expires_at&&new Date(offer.expires_at)<new Date())return c.json({code:"OFFER_EXPIRED",message:"This offer has expired"},409);const docs=(await pool.query("select content_hash from offer_documents where tenant_id=$1 and offer_id=$2 and status='GENERATED' order by document_type,version desc",[x.tenantId,id])).rows;if(docs.length<2)return c.json({code:"DOCUMENTS_REQUIRED",message:"Offer documents are incomplete"},409);const signedAt=new Date().toISOString(),signatureHash=sha([id,b.signerName,signedAt,...docs.map((d:any)=>d.content_hash)].join("|"));await withTransaction(async client=>{await client.query("insert into offer_signatures(id,tenant_id,offer_id,signer_name,signature_hash,accepted_terms) values($1,$2,$3,$4,$5,true) on conflict(tenant_id,offer_id,signer_role) do update set signer_name=excluded.signer_name,signature_hash=excluded.signature_hash,accepted_terms=true,signed_at=now()",[randomUUID(),x.tenantId,id,b.signerName,signatureHash]);await client.query("update offers set status='ACCEPTED',accepted_at=now(),updated_at=now() where tenant_id=$1 and id=$2",[x.tenantId,id]);await writeOutbox(client,createEvent({eventType:Events.offerAccepted,eventVersion:1,producer:"offers",correlationId:x.correlationId,tenantId:x.tenantId,payload:{...offer,status:"ACCEPTED",acceptedAt:signedAt,signatureHash}}));});return c.json({id,status:"ACCEPTED",signedAt,signatureHash});
});

app.post("/v1/offers/:id/decline",async c=>{const x=context(c.req.raw.headers),b=z.object({reason:z.string().min(1)}).parse(await c.req.json()),id=c.req.param("id"),value=await withTransaction(async client=>{const{rows}=await client.query("update offers set status='DECLINED',decline_reason=$3,declined_at=now(),updated_at=now() where tenant_id=$1 and id=$2 and status='ISSUED' returning *",[x.tenantId,id,b.reason]);if(!rows[0])return null;await writeOutbox(client,createEvent({eventType:Events.offerDeclined,eventVersion:1,producer:"offers",correlationId:x.correlationId,tenantId:x.tenantId,payload:rows[0]}));return rows[0];});return value?c.json(value):c.json({code:"INVALID_STATE",message:"Offer cannot be declined"},409);});

async function transition(x:any,id:string,status:string,eventType:string,extra:Record<string,unknown>={}){return withTransaction(async client=>{const{rows}=await client.query("update offers set status=$3,issued_at=case when $3='ISSUED' then now() else issued_at end,updated_at=now() where tenant_id=$1 and id=$2 returning *",[x.tenantId,id,status]);if(!rows[0])return null;await writeOutbox(client,createEvent({eventType,eventVersion:1,producer:"offers",correlationId:x.correlationId,tenantId:x.tenantId,payload:{...rows[0],...extra}}));return rows[0];});}

app.get("/v1/offers/templates",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from offer_templates where tenant_id=$1 and active=true order by name",[x.tenantId])).rows);});
app.post("/v1/offers/templates",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into offer_templates(id,tenant_id,name,organisation_id,template) values($1,$2,$3,$4,$5::jsonb)",[id,x.tenantId,String(b.name),b.organisationId||null,JSON.stringify(b.template||{})]);return c.json({id},201);});
app.get("/v1/offers/:id/versions",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from offer_versions where tenant_id=$1 and offer_id=$2 order by version desc",[x.tenantId,c.req.param("id")])).rows);});
app.get("/v1/offers/:id/approvals",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from offer_approvals where tenant_id=$1 and offer_id=$2 order by approval_type",[x.tenantId,c.req.param("id")])).rows);});
app.post("/v1/offers/:id/approvals",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into offer_approvals(id,tenant_id,offer_id,approval_type,requested_from) values($1,$2,$3,$4,$5) on conflict(tenant_id,offer_id,approval_type) do update set status='PENDING',requested_from=excluded.requested_from,requested_at=now(),decision_by=null,decision_note=null,decided_at=null",[id,x.tenantId,c.req.param("id"),String(b.approvalType),b.requestedFrom||null]);return c.json({id,status:"PENDING"},201);});
app.patch("/v1/offers/:offerId/approvals/:id",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,status=String(b.status);if(!["APPROVED","REJECTED"].includes(status))return c.json({code:"INVALID_STATUS",message:"Approval status must be APPROVED or REJECTED"},400);const{rows}=await pool.query("update offer_approvals set status=$4,decision_by=$5,decision_note=$6,decided_at=now() where tenant_id=$1 and offer_id=$2 and id=$3 returning *",[x.tenantId,c.req.param("offerId"),c.req.param("id"),status,c.req.header("x-actor")||null,b.note||null]);return rows[0]?c.json(rows[0]):c.json({code:"NOT_FOUND",message:"Approval not found"},404);});
app.get("/v1/offers/approval-rules",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from offer_approval_rules where tenant_id=$1 and active=true order by organisation_id nulls first,approval_type",[x.tenantId])).rows);});
app.post("/v1/offers/approval-rules",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into offer_approval_rules(id,tenant_id,organisation_id,approval_type,condition,required) values($1,$2,$3,$4,$5::jsonb,$6)",[id,x.tenantId,b.organisationId||null,String(b.approvalType),JSON.stringify(b.condition||{}),b.required!==false]);return c.json({id},201);});

app.post("/v1/offers/:id/negotiations",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into offer_negotiations(id,tenant_id,offer_id,author_type,note,proposal) values($1,$2,$3,$4,$5,$6::jsonb)",[id,x.tenantId,c.req.param("id"),b.authorType||"RECRUITER",String(b.note),JSON.stringify(b.proposal||{})]);return c.json({id},201);});
app.get("/v1/offers/:id/negotiations",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from offer_negotiations where tenant_id=$1 and offer_id=$2 order by created_at",[x.tenantId,c.req.param("id")])).rows);});
app.get("/v1/offers/analytics/summary",async c=>{const x=context(c.req.raw.headers);const{rows}=await pool.query("select status,count(*)::int count from offers where tenant_id=$1 group by status",[x.tenantId]);const declines=(await pool.query("select decline_reason,count(*)::int count from offers where tenant_id=$1 and status='DECLINED' group by decline_reason order by count desc",[x.tenantId])).rows;return c.json({byStatus:Object.fromEntries(rows.map((r:any)=>[r.status,r.count])),declineReasons:declines});});

serve({fetch:app.fetch,port:Number(process.env.PORT||4116)});