import{randomUUID}from"node:crypto";import{serve}from"@hono/node-server";import{Hono}from"hono";import{z}from"zod";import{createEvent,Events}from"@raeburn/events";import{context,health,pool,withTransaction,writeOutbox}from"@raeburn/service-kit";
const app=new Hono();
app.get("/health",async c=>c.json(await health("offers")));
app.get("/v1/offers",async c=>{const x=context(c.req.raw.headers),applicationId=c.req.query("applicationId");const r=applicationId?await pool.query("select * from offers where tenant_id=$1 and application_id=$2 order by version desc",[x.tenantId,applicationId]):await pool.query("select * from offers where tenant_id=$1 order by created_at desc limit 250",[x.tenantId]);return c.json(r.rows);});
app.post("/v1/offers",async c=>{const x=context(c.req.raw.headers),b=z.object({applicationId:z.string(),compensation:z.record(z.string(),z.unknown()).default({}),equity:z.record(z.string(),z.unknown()).default({}),conditions:z.array(z.unknown()).default([])}).parse(await c.req.json()),id=randomUUID(),value={id,applicationId:b.applicationId,status:"DRAFT",version:1,compensation:b.compensation,equity:b.equity,conditions:b.conditions};await withTransaction(async client=>{await client.query("insert into offers(id,tenant_id,application_id,compensation,equity,conditions) values($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb)",[id,x.tenantId,b.applicationId,JSON.stringify(b.compensation),JSON.stringify(b.equity),JSON.stringify(b.conditions)]);await writeOutbox(client,createEvent({eventType:Events.offerCreated,eventVersion:1,producer:"offers",correlationId:x.correlationId,tenantId:x.tenantId,payload:value}));});return c.json(value,201);});
app.post("/v1/offers/:id/issue",async c=>{const x=context(c.req.raw.headers),value=await transition(x,c.req.param("id"),"ISSUED",Events.offerIssued);return value?c.json(value):c.json({code:"NOT_FOUND",message:"Offer not found"},404);});
app.post("/v1/offers/:id/accept",async c=>{const x=context(c.req.raw.headers),value=await transition(x,c.req.param("id"),"ACCEPTED",Events.offerAccepted);return value?c.json(value):c.json({code:"NOT_FOUND",message:"Offer not found"},404);});
app.post("/v1/offers/:id/decline",async c=>{const x=context(c.req.raw.headers),{rows}=await pool.query("update offers set status='DECLINED',updated_at=now() where tenant_id=$1 and id=$2 and status='ISSUED' returning *",[x.tenantId,c.req.param("id")]);return rows[0]?c.json(rows[0]):c.json({code:"INVALID_STATE",message:"Offer cannot be declined"},409);});
async function transition(x:any,id:string,status:string,eventType:string){return withTransaction(async client=>{const{rows}=await client.query("update offers set status=$3,updated_at=now() where tenant_id=$1 and id=$2 returning *",[x.tenantId,id,status]);if(!rows[0])return null;await writeOutbox(client,createEvent({eventType,eventVersion:1,producer:"offers",correlationId:x.correlationId,tenantId:x.tenantId,payload:rows[0]}));return rows[0];});}
serve({fetch:app.fetch,port:Number(process.env.PORT||4116)});