import{randomUUID}from"node:crypto";
import{serve}from"@hono/node-server";
import{Hono}from"hono";
import{z}from"zod";
import{createEvent}from"@raeburn/events";
import{context,health,pool,publish}from"@raeburn/service-kit";

const app=new Hono();
app.get("/health",async c=>c.json(await health("assessments")));

app.get("/v1/assessments",async c=>{const x=context(c.req.raw.headers),applicationId=c.req.query("applicationId");const r=applicationId?await pool.query("select * from assessments where tenant_id=$1 and application_id=$2 order by created_at desc",[x.tenantId,applicationId]):await pool.query("select * from assessments where tenant_id=$1 order by created_at desc limit 250",[x.tenantId]);return c.json(r.rows);});

app.get("/v1/assessments/templates",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from assessment_templates where tenant_id=$1 and active=true order by name",[x.tenantId])).rows);});
app.get("/v1/assessments/templates/:id/versions",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from assessment_template_versions where tenant_id=$1 and template_id=$2 order by version desc",[x.tenantId,c.req.param("id")])).rows);});
app.post("/v1/assessments/templates",async c=>{const x=context(c.req.raw.headers),b=z.object({name:z.string(),type:z.string(),instructions:z.string().optional(),rubric:z.record(z.string(),z.unknown()).default({}),accessibilityOptions:z.record(z.string(),z.unknown()).default({})}).parse(await c.req.json()),id=randomUUID(),snapshot={...b,version:1};await pool.query("insert into assessment_templates(id,tenant_id,name,type,instructions,rubric,accessibility_options) values($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb)",[id,x.tenantId,b.name,b.type,b.instructions||null,JSON.stringify(b.rubric),JSON.stringify(b.accessibilityOptions)]);await pool.query("insert into assessment_template_versions(id,tenant_id,template_id,version,snapshot,created_by) values($1,$2,$3,1,$4::jsonb,$5)",[randomUUID(),x.tenantId,id,JSON.stringify(snapshot),c.req.header("x-actor")||null]);return c.json({id,version:1},201);});
app.patch("/v1/assessments/templates/:id",async c=>{const x=context(c.req.raw.headers),id=c.req.param("id"),b=(await c.req.json()) as any,current=(await pool.query("select * from assessment_templates where tenant_id=$1 and id=$2",[x.tenantId,id])).rows[0];if(!current)return c.json({code:"NOT_FOUND",message:"Assessment template not found"},404);const version=Number(current.version)+1,snapshot={name:b.name??current.name,type:b.type??current.type,instructions:b.instructions??current.instructions,rubric:b.rubric??current.rubric,accessibilityOptions:b.accessibilityOptions??current.accessibility_options,version};await pool.query("update assessment_templates set name=$3,type=$4,instructions=$5,rubric=$6::jsonb,accessibility_options=$7::jsonb,version=$8 where tenant_id=$1 and id=$2",[x.tenantId,id,snapshot.name,snapshot.type,snapshot.instructions||null,JSON.stringify(snapshot.rubric),JSON.stringify(snapshot.accessibilityOptions),version]);await pool.query("insert into assessment_template_versions(id,tenant_id,template_id,version,snapshot,created_by) values($1,$2,$3,$4,$5::jsonb,$6)",[randomUUID(),x.tenantId,id,version,JSON.stringify(snapshot),c.req.header("x-actor")||null]);return c.json({id,...snapshot});});

app.post("/v1/assessments",async c=>{const x=context(c.req.raw.headers),b=z.object({applicationId:z.string(),type:z.string(),title:z.string(),instructions:z.string().optional(),templateId:z.string().optional(),dueAt:z.string().datetime().optional(),blindReview:z.boolean().default(false),accessibilityAdjustments:z.record(z.string(),z.unknown()).default({})}).parse(await c.req.json()),id=randomUUID();let version:number|null=null,instructions=b.instructions||null,type=b.type;if(b.templateId){const t=(await pool.query("select * from assessment_templates where tenant_id=$1 and id=$2 and active=true",[x.tenantId,b.templateId])).rows[0];if(!t)return c.json({code:"TEMPLATE_NOT_FOUND",message:"Assessment template not found"},404);version=t.version;instructions=instructions||t.instructions;type=t.type;}await pool.query("insert into assessments(id,tenant_id,application_id,type,title,instructions,template_id,template_version,due_at,blind_review,accessibility_adjustments) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb)",[id,x.tenantId,b.applicationId,type,b.title,instructions,b.templateId||null,version,b.dueAt||null,b.blindReview,JSON.stringify(b.accessibilityAdjustments)]);await publish(createEvent({eventType:"assessment.assigned.v1",eventVersion:1,producer:"assessments",correlationId:x.correlationId,tenantId:x.tenantId,payload:{id,applicationId:b.applicationId,title:b.title,dueAt:b.dueAt||null}}));return c.json({id,status:"CREATED",templateVersion:version},201);});

app.post("/v1/assessments/:id/submit",async c=>{const x=context(c.req.raw.headers),b=z.object({content:z.record(z.string(),z.unknown()).default({}),documentIds:z.array(z.string()).default([]),integrity:z.record(z.string(),z.unknown()).default({})}).parse(await c.req.json()),assessmentId=c.req.param("id"),assessment=(await pool.query("select * from assessments where tenant_id=$1 and id=$2",[x.tenantId,assessmentId])).rows[0];if(!assessment)return c.json({code:"NOT_FOUND",message:"Assessment not found"},404);if(!["CREATED","EXTENDED"].includes(assessment.status))return c.json({code:"INVALID_STATE",message:"Assessment is not open for submission"},409);if(assessment.due_at&&new Date(assessment.due_at)<new Date())return c.json({code:"DEADLINE_PASSED",message:"Assessment deadline has passed. Request an extension before submitting."},409);const id=randomUUID();await pool.query("insert into assessment_submissions(id,tenant_id,assessment_id,content,document_ids,integrity) values($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb)",[id,x.tenantId,assessmentId,JSON.stringify(b.content),JSON.stringify(b.documentIds),JSON.stringify(b.integrity)]);await pool.query("update assessments set status='SUBMITTED',updated_at=now() where tenant_id=$1 and id=$2",[x.tenantId,assessmentId]);await publish(createEvent({eventType:"assessment.submitted.v1",eventVersion:1,producer:"assessments",correlationId:x.correlationId,tenantId:x.tenantId,payload:{id:assessmentId,applicationId:assessment.application_id,submissionId:id}}));return c.json({id,status:"SUBMITTED"},201);});

app.post("/v1/assessments/:id/extensions",async c=>{const x=context(c.req.raw.headers),b=z.object({reason:z.string().min(1),requestedDueAt:z.string().datetime().optional()}).parse(await c.req.json()),assessmentId=c.req.param("id"),id=randomUUID();const a=(await pool.query("select * from assessments where tenant_id=$1 and id=$2",[x.tenantId,assessmentId])).rows[0];if(!a)return c.json({code:"NOT_FOUND",message:"Assessment not found"},404);await pool.query("insert into assessment_extensions(id,tenant_id,assessment_id,requested_due_at,reason) values($1,$2,$3,$4,$5)",[id,x.tenantId,assessmentId,b.requestedDueAt||null,b.reason]);await pool.query("update assessments set extension_status='REQUESTED',extension_request=$3::jsonb,updated_at=now() where tenant_id=$1 and id=$2",[x.tenantId,assessmentId,JSON.stringify(b)]);await publish(createEvent({eventType:"assessment.extension_requested.v1",eventVersion:1,producer:"assessments",correlationId:x.correlationId,tenantId:x.tenantId,payload:{assessmentId,applicationId:a.application_id,extensionId:id,request:b}}));return c.json({id,status:"REQUESTED"},201);});
app.patch("/v1/assessments/:assessmentId/extensions/:id",async c=>{const x=context(c.req.raw.headers),b=z.object({status:z.enum(["APPROVED","DECLINED"]),dueAt:z.string().datetime().optional(),note:z.string().optional()}).parse(await c.req.json()),ext=(await pool.query("select * from assessment_extensions where tenant_id=$1 and assessment_id=$2 and id=$3",[x.tenantId,c.req.param("assessmentId"),c.req.param("id")])).rows[0];if(!ext)return c.json({code:"NOT_FOUND",message:"Extension request not found"},404);await pool.query("update assessment_extensions set status=$4,decision_by=$5,decision_note=$6,decided_at=now() where tenant_id=$1 and assessment_id=$2 and id=$3",[x.tenantId,c.req.param("assessmentId"),c.req.param("id"),b.status,c.req.header("x-actor")||null,b.note||null]);if(b.status==="APPROVED"){const due=b.dueAt||ext.requested_due_at;if(!due)return c.json({code:"DUE_DATE_REQUIRED",message:"Approved extensions require a new due date"},400);await pool.query("update assessments set status='EXTENDED',extension_status='APPROVED',due_at=$3,updated_at=now() where tenant_id=$1 and id=$2",[x.tenantId,c.req.param("assessmentId"),due]);}else await pool.query("update assessments set extension_status='DECLINED',updated_at=now() where tenant_id=$1 and id=$2",[x.tenantId,c.req.param("assessmentId")]);await publish(createEvent({eventType:"assessment.extension_decided.v1",eventVersion:1,producer:"assessments",correlationId:x.correlationId,tenantId:x.tenantId,payload:{assessmentId:c.req.param("assessmentId"),extensionId:c.req.param("id"),status:b.status}}));return c.json({id:c.req.param("id"),status:b.status});});
app.get("/v1/assessments/:id/extensions",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from assessment_extensions where tenant_id=$1 and assessment_id=$2 order by created_at desc",[x.tenantId,c.req.param("id")])).rows);});

app.get("/v1/assessments/:id/submissions",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from assessment_submissions where tenant_id=$1 and assessment_id=$2 order by submitted_at desc",[x.tenantId,c.req.param("id")])).rows);});
app.post("/v1/assessments/:id/reviews",async c=>{const x=context(c.req.raw.headers),b=z.object({reviewerId:z.string().optional(),scores:z.record(z.string(),z.unknown()).default({}),feedback:z.string().optional(),candidateFeedback:z.string().optional(),publishFeedback:z.boolean().default(false)}).parse(await c.req.json()),id=randomUUID(),reviewerId=b.reviewerId||c.req.header("x-actor")||"";await pool.query("insert into assessment_reviews(id,tenant_id,assessment_id,reviewer_id,scores,feedback) values($1,$2,$3,$4,$5::jsonb,$6) on conflict(tenant_id,assessment_id,reviewer_id) do update set scores=excluded.scores,feedback=excluded.feedback",[id,x.tenantId,c.req.param("id"),reviewerId,JSON.stringify(b.scores),b.feedback||null]);if(b.candidateFeedback!==undefined)await pool.query("update assessments set candidate_feedback=$3,feedback_visible_at=case when $4 then now() else null end,status='REVIEWED',updated_at=now() where tenant_id=$1 and id=$2",[x.tenantId,c.req.param("id"),b.candidateFeedback,b.publishFeedback]);return c.json({id},201);});
app.get("/v1/assessments/:id/reviews",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from assessment_reviews where tenant_id=$1 and assessment_id=$2 order by created_at",[x.tenantId,c.req.param("id")])).rows);});
app.post("/v1/assessments/:id/publish-feedback",async c=>{const x=context(c.req.raw.headers),{rows}=await pool.query("update assessments set feedback_visible_at=now(),updated_at=now() where tenant_id=$1 and id=$2 and candidate_feedback is not null returning *",[x.tenantId,c.req.param("id")]);if(!rows[0])return c.json({code:"NO_FEEDBACK",message:"Candidate feedback must be recorded before publishing"},409);await publish(createEvent({eventType:"assessment.feedback_published.v1",eventVersion:1,producer:"assessments",correlationId:x.correlationId,tenantId:x.tenantId,payload:{assessmentId:rows[0].id,applicationId:rows[0].application_id}}));return c.json(rows[0]);});

serve({fetch:app.fetch,port:Number(process.env.PORT||4115)});