import {randomUUID} from "node:crypto";import {serve} from "@hono/node-server";import {Hono} from "hono";import {SignJWT} from "jose";import {CreateApplicationContract} from "@raeburn/contracts";import {createEvent,Events} from "@raeburn/events";import {context,health,pool,withTransaction,writeOutbox} from "@raeburn/service-kit";
const app=new Hono();const CANDIDATES=process.env.CANDIDATES_URL||"http://localhost:4102";const JOBS=process.env.JOBS_URL||"http://localhost:4101";const ATTRIBUTION=process.env.ATTRIBUTION_URL||"http://localhost:4104";const uploadSecret=()=>new TextEncoder().encode(process.env.APPLICATION_UPLOAD_SECRET||process.env.AUTH_SECRET||"change-me");
app.get("/health",async c=>c.json(await health("applications")));
app.post("/v1/applications",async c=>{const x=context(c.req.raw.headers);const body=CreateApplicationContract.parse(await c.req.json());const headers={"content-type":"application/json","x-tenant-id":x.tenantId,"x-correlation-id":x.correlationId};
 const jobRes=await fetch(JOBS+"/v1/jobs/"+body.jobId,{headers});if(!jobRes.ok)return c.json({code:"JOB_NOT_AVAILABLE",message:"Vacancy not available",correlationId:x.correlationId},409);const job:any=await jobRes.json();if(job.status!=="PUBLISHED")return c.json({code:"JOB_NOT_PUBLISHED",message:"Vacancy is not accepting applications",correlationId:x.correlationId},409);
 const candRes=await fetch(CANDIDATES+"/v1/candidates/resolve",{method:"POST",headers,body:JSON.stringify(body.candidate)});if(!candRes.ok)return c.json({code:"CANDIDATE_RESOLUTION_FAILED",message:"Could not resolve candidate",correlationId:x.correlationId},502);const candidate:any=await candRes.json();
 const id=randomUUID();const application=await withTransaction(async client=>{const {rows}=await client.query("insert into applications(id,tenant_id,job_id,candidate_id,right_to_work,availability,cover_note,privacy_notice_version,privacy_accepted_at,attribution,answers) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11::jsonb) returning *",[id,x.tenantId,body.jobId,candidate.id,body.rightToWork||null,body.availability||null,body.coverNote||null,body.privacyNoticeVersion,body.privacyAcceptedAt,JSON.stringify(body.attribution),JSON.stringify(body.answers)]);const value=map(rows[0]);await writeOutbox(client,createEvent({eventType:Events.applicationCreated,eventVersion:1,producer:"applications",correlationId:x.correlationId,tenantId:x.tenantId,payload:{...value,candidate,job}}));return value;});
 fetch(ATTRIBUTION+"/v1/attribution/conversions",{method:"POST",headers,body:JSON.stringify({applicationId:id,jobId:body.jobId,candidateId:candidate.id,...body.attribution})}).catch(()=>{});
 const documentUploadToken=await new SignJWT({tenantId:x.tenantId,applicationId:id,candidateId:candidate.id,scope:"candidate-document-upload"}).setProtectedHeader({alg:"HS256"}).setIssuedAt().setExpirationTime("15m").sign(uploadSecret());
 return c.json({...application,documentUploadToken},201);});
app.get("/v1/applications/:id",async c=>{const x=context(c.req.raw.headers);const{rows}=await pool.query("select * from applications where tenant_id=$1 and id=$2",[x.tenantId,c.req.param("id")]);if(!rows[0])return c.json({code:"NOT_FOUND",message:"Application not found",correlationId:x.correlationId},404);return c.json(map(rows[0]));});
serve({fetch:app.fetch,port:Number(process.env.PORT||4103)});function map(r:any){return{id:r.id,tenantId:r.tenant_id,jobId:r.job_id,candidateId:r.candidate_id,rightToWork:r.right_to_work,availability:r.availability,coverNote:r.cover_note,privacyNoticeVersion:r.privacy_notice_version,privacyAcceptedAt:r.privacy_accepted_at,attribution:r.attribution,answers:r.answers,createdAt:r.created_at};}
