"use client";
import{FormEvent,useState}from"react";import{useRouter}from"next/navigation";

export default function PrivacyManager({requests,candidates}:{requests:any[];candidates:any[]}){
 const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);const r=await fetch("/api/talent/privacy/requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({candidateId:String(f.get("candidateId")),type:String(f.get("type"))})});setBusy(false);if(!r.ok){setMessage("Could not create privacy request.");return;}router.refresh();}
 async function reauth(){const password=window.prompt("Re-enter your Raeburn Talent password to authorise this sensitive action.");if(!password)return null;const totp=window.prompt("MFA code (leave blank if your account does not use TOTP).")||undefined;const r=await fetch("/api/talent/identity/reauth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password,...(totp?{totp}:{})})});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage(d.message||"Re-authentication failed.");return null;}return d.reauthToken as string;}
 async function verify(id:string){setBusy(true);setMessage("");const r=await fetch("/api/talent/privacy/requests/"+id+"/verify-identity",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({method:"MANUAL_VERIFICATION"})});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)setMessage(d.message||"Identity verification could not be recorded.");router.refresh();}
 async function approve(id:string){setBusy(true);setMessage("");const token=await reauth();if(!token){setBusy(false);return;}const r=await fetch("/api/talent/privacy/requests/"+id+"/approve",{method:"POST",headers:{"content-type":"application/json","x-reauth-token":token},body:JSON.stringify({decision:"APPROVED"})});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)setMessage(d.message||"Privacy request could not be approved.");router.refresh();}
 async function execute(id:string){setBusy(true);setMessage("");const token=await reauth();if(!token){setBusy(false);return;}const r=await fetch("/api/talent/privacy/requests/"+id+"/execute",{method:"POST",headers:{"x-reauth-token":token}});const d=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setMessage(d.error||d.message||"Privacy request failed.");router.refresh();return;}router.refresh();}
 return <><div className="card"><h2>Create privacy request</h2><p>Requests must pass identity verification and independent approval before fulfilment.</p><form onSubmit={create}><p><select name="candidateId" required>{candidates.map(c=><option value={c.id} key={c.id}>{c.name} — {c.email}</option>)}</select></p><p><select name="type"><option>DSAR</option><option>ANONYMISE</option><option>DELETE</option></select></p><button disabled={busy||!candidates.length}>Create request</button></form>{message&&<p role="alert">{message}</p>}</div><table style={{marginTop:18}}><thead><tr><th>Created</th><th>Candidate</th><th>Type</th><th>Status</th><th>Governance</th><th>Actions</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString("en-GB")}</td><td>{r.candidate_id}</td><td>{r.type}</td><td>{r.status}</td><td>{r.identity_verified_at?"Identity verified":"Identity pending"} · {r.approved_at?"Approved":"Approval pending"}</td><td><div className="headerActions">{!r.identity_verified_at&&<button disabled={busy} onClick={()=>verify(r.id)}>Verify identity</button>}{r.identity_verified_at&&!r.approved_at&&!r.rejected_at&&<button disabled={busy} onClick={()=>approve(r.id)}>Approve</button>}{r.approved_at&&!r.completed_at&&<button disabled={busy} onClick={()=>execute(r.id)}>Execute</button>}{r.completed_at&&r.type==="DSAR"&&<><a className="button secondary" href={"/api/talent/privacy/requests/"+r.id+"/export?format=html"} target="_blank">Human export</a><a className="button secondary" href={"/api/talent/privacy/requests/"+r.id+"/export?format=json"} target="_blank">JSON</a></>}</div></td></tr>)}</tbody></table></>;
}
