"use client";
import{startRegistration}from"@simplewebauthn/browser";
import{useState}from"react";import{useRouter}from"next/navigation";
export default function SecuritySettings({sessions}:{sessions:any[]}){
 const router=useRouter(),[setup,setSetup]=useState<any>(null),[code,setCode]=useState(""),[message,setMessage]=useState(""),[reauthPassword,setReauthPassword]=useState(""),[reauthTotp,setReauthTotp]=useState("");
 async function start(){const r=await fetch("/api/talent/identity/mfa/setup",{method:"POST"}),b=await r.json();if(!r.ok){setMessage(b.message||"Could not start MFA setup");return;}setSetup(b);}
 async function verify(){const r=await fetch("/api/talent/identity/mfa/verify-setup",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code})}),b=await r.json();if(!r.ok){setMessage(b.message||"Invalid code");return;}setMessage("MFA enabled.");setSetup(null);router.refresh();}
 async function passkey(){setMessage("");const o=await fetch("/api/talent/identity/passkeys/register/options",{method:"POST"}),options=await o.json();if(!o.ok){setMessage(options.message||"Could not start passkey registration.");return;}const{challengeId,...optionsJSON}=options;try{const response=await startRegistration({optionsJSON});const r=await fetch("/api/talent/identity/passkeys/register/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({challengeId,credential:response})}),b=await r.json();setMessage(r.ok?"Passkey registered on this account.":b.message||"Passkey registration failed.");}catch(e){setMessage(e instanceof Error?e.message:"Passkey registration cancelled.");}}
 async function revoke(id:string){await fetch("/api/talent/identity/sessions/"+id,{method:"DELETE"});router.refresh();}
 async function reauthorise(){setMessage("");const r=await fetch("/api/auth/reauth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password:reauthPassword,totp:reauthTotp||undefined})}),b=await r.json().catch(()=>({}));if(!r.ok){setMessage(b.message||"Privileged re-authentication failed.");return;}setReauthPassword("");setReauthTotp("");setMessage("Privileged actions authorised for five minutes.");}
 return <><div className="card"><h2>Privileged access</h2><p>Confirm your credentials before changing identity providers, user access, privacy execution or AI governance. Authorisation lasts five minutes.</p><p><input type="password" value={reauthPassword} onChange={e=>setReauthPassword(e.target.value)} placeholder="Password" autoComplete="current-password"/></p><p><input value={reauthTotp} onChange={e=>setReauthTotp(e.target.value)} inputMode="numeric" maxLength={6} placeholder="Authenticator code if enabled"/></p><button type="button" onClick={reauthorise}>Authorise privileged actions</button></div><div className="card"><h2>Multi-factor authentication</h2><p>Use a TOTP authenticator for an additional sign-in factor.</p>{!setup?<button onClick={start}>Set up authenticator</button>:<div><p>Authenticator secret: <code>{setup.secret}</code></p><p>You can enter the provided <code>otpauth://</code> URI into a compatible authenticator if QR import is unavailable.</p><input value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" maxLength={6} placeholder="6-digit code"/><button onClick={verify}>Verify and enable</button></div>}</div><div className="card"><h2>Passkeys</h2><p>Register a WebAuthn passkey backed by your device, password manager or hardware security key.</p><button onClick={passkey}>Register passkey</button></div>{message&&<p role="alert">{message}</p>}<h2>Sessions</h2><table><thead><tr><th>Created</th><th>Last used</th><th>Expires</th><th>Status</th><th></th></tr></thead><tbody>{sessions.map(s=><tr key={s.id}><td>{new Date(s.created_at).toLocaleString("en-GB")}</td><td>{s.last_seen_at?new Date(s.last_seen_at).toLocaleString("en-GB"):"—"}</td><td>{new Date(s.expires_at).toLocaleString("en-GB")}</td><td>{s.status}</td><td>{s.status==="ACTIVE"&&<button onClick={()=>revoke(s.id)}>Revoke</button>}</td></tr>)}</tbody></table></>;
}
