"use client";
import{useRef,useState}from"react";
import{useRouter}from"next/navigation";
const stages=["APPLIED","SCREENING","REVIEW","SHORTLIST","INTERVIEW","FINAL_INTERVIEW","OFFER","HIRED","REJECTED","WITHDRAWN","ON_HOLD","TALENT_POOL"];
const evidenceStages=new Set(["REVIEW","SHORTLIST","INTERVIEW","FINAL_INTERVIEW","OFFER"]);
export default function StageSelect({applicationId,current}:{applicationId:string;current:string}){
 const router=useRouter(),[state,setState]=useState(current),[busy,setBusy]=useState(false),[undo,setUndo]=useState<string|null>(null),[pending,setPending]=useState<string|null>(null),[reasons,setReasons]=useState<any[]>([]),[reasonCode,setReasonCode]=useState(""),[rationale,setRationale]=useState(""),[evidence,setEvidence]=useState(""),[error,setError]=useState(""),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function needsEvidence(stage:string){return stage==="HIRED"||(stage==="REJECTED"&&evidenceStages.has(state));}
 async function requestChange(stage:string){setError("");if(stage===state)return;if(needsEvidence(stage)){setPending(stage);setReasonCode("");setRationale("");setEvidence("");const type=stage==="HIRED"?"HIRE":"REJECT";const r=await fetch("/api/talent/workflow/decision-reasons?type="+type),b=await r.json().catch(()=>[]);setReasons(r.ok&&Array.isArray(b)?b:[]);return;}await change(stage);}
 async function change(stage:string,payload:Record<string,unknown>={}){const previous=state;setBusy(true);const r=await fetch("/api/talent/workflow/"+applicationId+"/stage",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({stage,...payload})}),b=await r.json().catch(()=>({}));setBusy(false);if(!r.ok){setError(b.message||"Stage change could not be completed.");return false;}setState(stage);setPending(null);setError("");if(stage!=="HIRED"&&stage!=="REJECTED"){setUndo(previous);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setUndo(null),8000);}else setUndo(null);router.refresh();return true;}
 async function confirmDecision(){const refs=evidence.split("\n").map(x=>x.trim()).filter(Boolean);if(!reasonCode||!rationale.trim()||!refs.length){setError("Select a reason, explain the decision and provide at least one evidence reference.");return;}if(pending)await change(pending,{reasonCode,rationale:rationale.trim(),evidence:refs.map(reference=>({reference}))});}
 async function undoChange(){if(!undo)return;const target=undo;setBusy(true);const r=await fetch("/api/talent/workflow/"+applicationId+"/stage",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({stage:target})});setBusy(false);if(r.ok){setState(target);setUndo(null);setError("");router.refresh();}else{const b=await r.json().catch(()=>({}));setError(b.message||"Previous stage could not be restored.");setUndo(null);}}
 return <div className="stageControl"><select value={state} disabled={busy||!!pending} onChange={e=>requestChange(e.target.value)}>{stages.map(s=><option key={s}>{s}</option>)}</select>{undo&&<button type="button" className="secondary undoButton" disabled={busy} onClick={undoChange}>Undo</button>}{pending&&<div className="card" style={{marginTop:10,minWidth:320}}><h3>{pending==="HIRED"?"Record final hiring evidence":"Record rejection evidence"}</h3><p>Only job-related evidence should be recorded. Do not use protected characteristics or reasonable-adjustment information.</p><label>Decision reason<select value={reasonCode} onChange={e=>setReasonCode(e.target.value)}><option value="">Select reason</option>{reasons.map((x:any)=><option key={x.code} value={x.code}>{x.label}</option>)}</select></label><label>Decision rationale<textarea value={rationale} onChange={e=>setRationale(e.target.value)} rows={4} placeholder="Explain how the evidence relates to the published selection criteria."/></label><label>Evidence references<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} rows={4} placeholder={"One evidence reference per line\nExample: Interview scorecard INT-123"}/></label><div className="headerActions"><button type="button" disabled={busy} onClick={confirmDecision}>Confirm {pending==="HIRED"?"hire":"rejection"}</button><button type="button" className="secondary" disabled={busy} onClick={()=>{setPending(null);setError("");}}>Cancel</button></div></div>}{error&&<p role="alert">{error}</p>}</div>;
}