"use client";
import{useEffect,useState}from"react";

export default function TalentPoolsWorkspace({initialPools=[]}:{initialPools:any[]}){
 const[pools,setPools]=useState(initialPools),[poolId,setPoolId]=useState(initialPools[0]?.id||""),[health,setHealth]=useState<any>(null),[suggestions,setSuggestions]=useState<any[]>([]),[nurture,setNurture]=useState<any[]>([]),[busy,setBusy]=useState(false);
 async function load(id=poolId){if(!id)return;const[h,s,n]=await Promise.all([fetch("/api/talent/talent-pools/"+id+"/health"),fetch("/api/talent/talent-pools/"+id+"/suggestions"),fetch("/api/talent/talent-pools/nurture/due")]);if(h.ok)setHealth(await h.json());if(s.ok)setSuggestions(await s.json());if(n.ok)setNurture((await n.json()).filter((x:any)=>x.pool_id===id));}
 useEffect(()=>{void load(poolId)},[poolId]);
 async function refresh(){if(!poolId)return;setBusy(true);await fetch("/api/talent/talent-pools/"+poolId+"/suggestions/refresh",{method:"POST"});await load();setBusy(false);}
 async function planNurture(){if(!poolId)return;setBusy(true);await fetch("/api/talent/talent-pools/"+poolId+"/nurture/plan",{method:"POST"});await load();setBusy(false);}
 async function decide(candidateId:string,decision:"accept"|"reject"){await fetch("/api/talent/talent-pools/"+poolId+"/suggestions/"+candidateId+"/"+decision,{method:"POST"});await load();}
 async function complete(id:string){await fetch("/api/talent/talent-pools/nurture/"+id+"/complete",{method:"POST"});await load();}
 async function createPool(){const name=prompt("Pool name");if(!name)return;const skills=(prompt("Priority skills (comma separated)")||"").split(",").map(x=>x.trim()).filter(Boolean);const r=await fetch("/api/talent/talent-pools",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,criteria:{skills},nurtureEnabled:true,reengageAfterDays:90})});if(r.ok){location.reload();}}
 return <div className="workspaceStack">
  <section className="card"><div className="sectionHead"><div><h2>Talent communities</h2><p>Explainable pool suggestions, health and re-engagement.</p></div><button onClick={createPool}>Create pool</button></div>{pools.length?<div className="filterBar"><select value={poolId} onChange={e=>setPoolId(e.target.value)}>{pools.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button disabled={busy} onClick={refresh}>Refresh suggestions</button><button disabled={busy} onClick={planNurture}>Plan re-engagement</button></div>:<p>No pools yet.</p>}</section>
  {health&&<section className="stats"><div className="card"><h3>Pool health</h3><strong className="bigMetric">{health.healthScore}/100</strong><small>{health.explanation?.health}</small></div><div className="card"><h3>Members</h3><strong className="bigMetric">{health.memberCount}</strong></div><div className="card"><h3>Fresh</h3><strong className="bigMetric">{health.freshCount}</strong><small>{health.explanation?.fresh}</small></div><div className="card"><h3>Engaged</h3><strong className="bigMetric">{health.engagedCount}</strong><small>{health.explanation?.engaged}</small></div></section>}
  <section className="card"><h2>Automatic suggestions</h2><p>Suggestions are evidence-based and require recruiter approval.</p>{suggestions.length?suggestions.map(s=><div className="rowCard" key={s.candidate_id}><div><a href={"/candidates/"+s.candidate_id}><strong>{s.candidate?.name||s.candidate_id}</strong></a><p>Match score {Number(s.score).toFixed(0)}/100 · {JSON.stringify(s.evidence)}</p></div><div className="headerActions"><button onClick={()=>decide(s.candidate_id,"accept")}>Add</button><button onClick={()=>decide(s.candidate_id,"reject")}>Dismiss</button></div></div>):<p>No current suggestions. Refresh to evaluate the candidate database.</p>}</section>
  <section className="card"><h2>Re-engagement queue</h2>{nurture.length?nurture.map(n=><div className="rowCard" key={n.id}><div><a href={"/candidates/"+n.candidate_id}><strong>{n.candidate?.name||n.candidate_id}</strong></a><p>{n.reason}</p></div><button onClick={()=>complete(n.id)}>Mark handled</button></div>):<p>No candidates currently need re-engagement.</p>}</section>
 </div>;
}
