import{randomUUID}from"node:crypto";
import{serve}from"@hono/node-server";
import{Hono}from"hono";
import{z}from"zod";
import{createEvent,Events}from"@raeburn/events";
import{context,health,pool,withTransaction,writeOutbox,installServiceRuntime}from"@raeburn/service-kit";

const app=new Hono();installServiceRuntime(app,"interviews");
const ScoreValue=z.union([z.number().min(1).max(5),z.object({score:z.number().min(1).max(5),evidence:z.string().min(1).optional()})]);

function requiredKeys(dimensions:any[]){return(dimensions||[]).filter(d=>d?.required!==false).map(d=>String(d.key));}
function scorePresent(scorecard:Record<string,unknown>,key:string){const v=scorecard[key];return typeof v==="number"||(typeof v==="object"&&v!==null&&typeof (v as any).score==="number");}

app.get("/health",async c=>c.json(await health("interviews")));

app.get("/v1/interviews",async c=>{const x=context(c.req.raw.headers),applicationId=c.req.query("applicationId");const r=applicationId?await pool.query("select * from interviews where tenant_id=$1 and application_id=$2 order by round",[x.tenantId,applicationId]):await pool.query("select * from interviews where tenant_id=$1 order by created_at desc limit 250",[x.tenantId]);return c.json(r.rows);});

app.post("/v1/interviews",async c=>{
 const x=context(c.req.raw.headers),b=z.object({applicationId:z.string(),round:z.number().int().positive().default(1),templateId:z.string().optional(),startsAt:z.string().datetime().optional(),endsAt:z.string().datetime().optional(),participants:z.array(z.string()).default([])}).parse(await c.req.json()),id=randomUUID();
 let template:any=null;if(b.templateId){template=(await pool.query("select * from interview_templates where tenant_id=$1 and id=$2 and active=true",[x.tenantId,b.templateId])).rows[0];if(!template)return c.json({code:"TEMPLATE_NOT_FOUND",message:"Interview template not found"},404);}
 const questions=template?.questions||[],dimensions=template?.score_dimensions||[],trainingPrompt=template?.instructions||"Record evidence independently before viewing panel feedback.";
 const value=await withTransaction(async client=>{
   const{rows}=await client.query("insert into interviews(id,tenant_id,application_id,round,starts_at,ends_at,participants,template_id,questions_snapshot,score_dimensions_snapshot,training_prompt,feedback_due_at) values($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9::jsonb,$10::jsonb,$11,case when $6::timestamptz is null then null else $6::timestamptz+interval '24 hours' end) returning *",[id,x.tenantId,b.applicationId,b.round,b.startsAt||null,b.endsAt||null,JSON.stringify(b.participants),b.templateId||null,JSON.stringify(questions),JSON.stringify(dimensions),trainingPrompt]);
   await writeOutbox(client,createEvent({eventType:Events.interviewRequested,eventVersion:1,producer:"interviews",correlationId:x.correlationId,tenantId:x.tenantId,payload:rows[0]}));return rows[0];
 });return c.json(value,201);
});

app.patch("/v1/interviews/:id/schedule",async c=>{
 const x=context(c.req.raw.headers),b=z.object({startsAt:z.string().datetime(),endsAt:z.string().datetime(),meetingUrl:z.string().url().optional(),participants:z.array(z.string()).default([])}).parse(await c.req.json()),id=c.req.param("id");
 const value=await withTransaction(async client=>{const{rows}=await client.query("update interviews set status='SCHEDULED',starts_at=$3,ends_at=$4,meeting_url=$5,participants=$6::jsonb,feedback_due_at=$4::timestamptz+interval '24 hours',reschedule_status=null,reschedule_request='{}'::jsonb where tenant_id=$1 and id=$2 returning *",[x.tenantId,id,b.startsAt,b.endsAt,b.meetingUrl||null,JSON.stringify(b.participants)]);if(!rows[0])return null;
 for(const reviewer of b.participants){await client.query("insert into interview_reminders(id,tenant_id,interview_id,reviewer_id,kind,scheduled_for) values($1,$2,$3,$4,'FEEDBACK_DUE',$5::timestamptz+interval '2 hours') on conflict(tenant_id,interview_id,reviewer_id,kind) do update set scheduled_for=excluded.scheduled_for,status='PENDING',sent_at=null",[randomUUID(),x.tenantId,id,reviewer,b.endsAt]);}
 await writeOutbox(client,createEvent({eventType:Events.interviewScheduled,eventVersion:1,producer:"interviews",correlationId:x.correlationId,tenantId:x.tenantId,payload:rows[0]}));return rows[0];});return value?c.json(value):c.json({code:"NOT_FOUND",message:"Interview not found"},404);
});

app.post("/v1/interviews/:id/declaration",async c=>{const x=context(c.req.raw.headers),b=z.object({reviewerId:z.string().optional(),conflictDeclared:z.boolean(),conflictDetail:z.string().optional(),trainingAcknowledged:z.boolean()}).parse(await c.req.json()),id=randomUUID(),reviewerId=b.reviewerId||c.req.header("x-actor")||"";if(!reviewerId)return c.json({code:"REVIEWER_REQUIRED",message:"Reviewer identity required"},400);await pool.query("insert into interviewer_declarations(id,tenant_id,interview_id,reviewer_id,conflict_declared,conflict_detail,training_acknowledged) values($1,$2,$3,$4,$5,$6,$7) on conflict(tenant_id,interview_id,reviewer_id) do update set conflict_declared=excluded.conflict_declared,conflict_detail=excluded.conflict_detail,training_acknowledged=excluded.training_acknowledged",[id,x.tenantId,c.req.param("id"),reviewerId,b.conflictDeclared,b.conflictDetail||null,b.trainingAcknowledged]);return c.json({ok:true});});

app.post("/v1/interviews/:id/feedback",async c=>{
 const x=context(c.req.raw.headers),b=z.object({reviewerId:z.string().optional(),scorecard:z.record(z.string(),ScoreValue),notes:z.string().optional(),recommendation:z.enum(["STRONG_YES","YES","MIXED","NO","STRONG_NO"]).optional()}).parse(await c.req.json()),interviewId=c.req.param("id"),reviewerId=b.reviewerId||c.req.header("x-actor")||"";
 const interview=(await pool.query("select * from interviews where tenant_id=$1 and id=$2",[x.tenantId,interviewId])).rows[0];if(!interview)return c.json({code:"NOT_FOUND",message:"Interview not found"},404);
 if(Array.isArray(interview.participants)&&interview.participants.length&&!interview.participants.includes(reviewerId))return c.json({code:"NOT_INTERVIEWER",message:"Reviewer is not assigned to this interview"},403);
 const declaration=(await pool.query("select * from interviewer_declarations where tenant_id=$1 and interview_id=$2 and reviewer_id=$3",[x.tenantId,interviewId,reviewerId])).rows[0];
 if(!declaration?.training_acknowledged)return c.json({code:"TRAINING_ACK_REQUIRED",message:"Acknowledge the interviewer training prompt before submitting feedback"},409);
 if(declaration?.conflict_declared)return c.json({code:"CONFLICT_DECLARED",message:"Feedback cannot be submitted while a conflict of interest is declared"},409);
 const missing=requiredKeys(interview.score_dimensions_snapshot).filter(k=>!scorePresent(b.scorecard,k));if(missing.length)return c.json({code:"MISSING_SCORES",message:"All mandatory score dimensions must be completed",missing},409);
 const id=randomUUID();await pool.query("insert into interview_feedback(id,tenant_id,interview_id,reviewer_id,scorecard,notes) values($1,$2,$3,$4,$5::jsonb,$6) on conflict(tenant_id,interview_id,reviewer_id) do update set scorecard=excluded.scorecard,notes=excluded.notes,submitted_at=now()",[id,x.tenantId,interviewId,reviewerId,JSON.stringify({...b.scorecard,_recommendation:b.recommendation||null}),b.notes||null]);return c.json({id,submitted:true});
});

app.get("/v1/interviews/:id/feedback",async c=>{
 const x=context(c.req.raw.headers),interviewId=c.req.param("id"),actor=c.req.header("x-actor")||"",interview=(await pool.query("select * from interviews where tenant_id=$1 and id=$2",[x.tenantId,interviewId])).rows[0];if(!interview)return c.json({code:"NOT_FOUND",message:"Interview not found"},404);
 const rows=(await pool.query("select f.*,d.conflict_declared,d.training_acknowledged from interview_feedback f left join interviewer_declarations d on d.tenant_id=f.tenant_id and d.interview_id=f.interview_id and d.reviewer_id=f.reviewer_id where f.tenant_id=$1 and f.interview_id=$2 order by f.created_at",[x.tenantId,interviewId])).rows,expected=Array.isArray(interview.participants)?interview.participants:[],submitted=new Set(rows.map((r:any)=>r.reviewer_id)),complete=expected.length===0||expected.every((p:string)=>submitted.has(p));
 return c.json({locked:!complete,expected:expected.length,submitted:rows.length,feedback:complete?rows:rows.filter((r:any)=>r.reviewer_id===actor)});
});

app.patch("/v1/interviews/:id/consensus",async c=>{
 const x=context(c.req.raw.headers),b=z.object({consensus:z.record(z.string(),z.unknown()).default({}),candidateQuestions:z.array(z.unknown()).default([])}).parse(await c.req.json()),id=c.req.param("id"),interview=(await pool.query("select * from interviews where tenant_id=$1 and id=$2",[x.tenantId,id])).rows[0];if(!interview)return c.json({code:"NOT_FOUND",message:"Interview not found"},404);
 const feedback=(await pool.query("select reviewer_id from interview_feedback where tenant_id=$1 and interview_id=$2",[x.tenantId,id])).rows,submitted=new Set(feedback.map((r:any)=>r.reviewer_id)),expected=Array.isArray(interview.participants)?interview.participants:[];
 if(expected.length&&expected.some((p:string)=>!submitted.has(p)))return c.json({code:"FEEDBACK_INCOMPLETE",message:"Panel consensus is locked until every assigned interviewer submits independent feedback",missing:expected.filter((p:string)=>!submitted.has(p))},409);
 const{rows}=await pool.query("update interviews set consensus=$3::jsonb,candidate_questions=$4::jsonb,consensus_opened_at=coalesce(consensus_opened_at,now()) where tenant_id=$1 and id=$2 returning *",[x.tenantId,id,JSON.stringify(b.consensus),JSON.stringify(b.candidateQuestions)]);return c.json(rows[0]);
});

app.post("/v1/interviews/:id/complete",async c=>{const x=context(c.req.raw.headers),id=c.req.param("id"),value=await withTransaction(async client=>{const{rows}=await client.query("update interviews set status='COMPLETED' where tenant_id=$1 and id=$2 and status='SCHEDULED' returning *",[x.tenantId,id]);if(!rows[0])return null;await writeOutbox(client,createEvent({eventType:Events.interviewCompleted,eventVersion:1,producer:"interviews",correlationId:x.correlationId,tenantId:x.tenantId,payload:rows[0]}));return rows[0];});return value?c.json(value):c.json({code:"INVALID_STATE",message:"Only a scheduled interview can be completed"},409);});

app.post("/v1/interviews/:id/reschedule-request",async c=>{const x=context(c.req.raw.headers),b=z.object({reason:z.string().min(1),preferredTimes:z.array(z.string()).default([])}).parse(await c.req.json()),id=c.req.param("id"),value=await withTransaction(async client=>{const{rows}=await client.query("update interviews set reschedule_status='REQUESTED',reschedule_request=$3::jsonb where tenant_id=$1 and id=$2 and status='SCHEDULED' returning *",[x.tenantId,id,JSON.stringify(b)]);if(!rows[0])return null;await writeOutbox(client,createEvent({eventType:Events.interviewRescheduleRequested,eventVersion:1,producer:"interviews",correlationId:x.correlationId,tenantId:x.tenantId,payload:{interviewId:id,applicationId:rows[0].application_id,request:b}}));return rows[0];});return value?c.json(value):c.json({code:"INVALID_STATE",message:"Interview is not available for rescheduling"},409);});
app.post("/v1/interviews/:id/reschedule-decision",async c=>{const x=context(c.req.raw.headers),b=z.object({status:z.enum(["APPROVED","DECLINED"])}).parse(await c.req.json()),id=c.req.param("id"),value=await withTransaction(async client=>{const{rows}=await client.query("update interviews set reschedule_status=$3 where tenant_id=$1 and id=$2 and reschedule_status='REQUESTED' returning *",[x.tenantId,id,b.status]);if(!rows[0])return null;await writeOutbox(client,createEvent({eventType:Events.interviewRescheduleDecided,eventVersion:1,producer:"interviews",correlationId:x.correlationId,tenantId:x.tenantId,payload:{interviewId:id,applicationId:rows[0].application_id,status:b.status}}));return rows[0];});return value?c.json(value):c.json({code:"INVALID_STATE",message:"No pending reschedule request"},409);});

app.get("/v1/interviews/templates",async c=>{const x=context(c.req.raw.headers),includeInactive=c.req.query("includeInactive")==="true";return c.json((await pool.query("select * from interview_templates where tenant_id=$1 and ($2::boolean or active=true) order by name",[x.tenantId,includeInactive])).rows);});
app.post("/v1/interviews/templates",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into interview_templates(id,tenant_id,name,interview_type,competency_framework_id,questions,score_dimensions,instructions) values($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8)",[id,x.tenantId,String(b.name),b.interviewType||"STRUCTURED",b.competencyFrameworkId||null,JSON.stringify(b.questions||[]),JSON.stringify(b.scoreDimensions||[]),b.instructions||null]);return c.json({id},201);});
app.patch("/v1/interviews/templates/:id",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json())as any;const{rows}=await pool.query("update interview_templates set name=coalesce($3,name),interview_type=coalesce($4,interview_type),competency_framework_id=case when $5::text is null then competency_framework_id else $5 end,questions=coalesce($6::jsonb,questions),score_dimensions=coalesce($7::jsonb,score_dimensions),instructions=case when $8::text is null then instructions else $8 end,active=coalesce($9,active),version=version+1 where tenant_id=$1 and id=$2 returning *",[x.tenantId,c.req.param("id"),b.name??null,b.interviewType??null,b.competencyFrameworkId??null,b.questions?JSON.stringify(b.questions):null,b.scoreDimensions?JSON.stringify(b.scoreDimensions):null,b.instructions??null,b.active??null]);return rows[0]?c.json(rows[0]):c.json({code:"NOT_FOUND",message:"Interview template not found"},404);});
app.get("/v1/interviews/competency-frameworks",async c=>{const x=context(c.req.raw.headers);return c.json((await pool.query("select * from competency_frameworks where tenant_id=$1 and active=true order by name",[x.tenantId])).rows);});
app.post("/v1/interviews/competency-frameworks",async c=>{const x=context(c.req.raw.headers),b=(await c.req.json()) as any,id=randomUUID();await pool.query("insert into competency_frameworks(id,tenant_id,name,description,competencies) values($1,$2,$3,$4,$5::jsonb)",[id,x.tenantId,String(b.name),b.description||null,JSON.stringify(b.competencies||[])]);return c.json({id},201);});

app.get("/v1/interviews/calibration",async c=>{const x=context(c.req.raw.headers),{rows}=await pool.query("select reviewer_id,scorecard from interview_feedback where tenant_id=$1",[x.tenantId]),by=new Map<string,{interviews:number;scores:number[];recommendations:Record<string,number>}>();for(const r of rows){const cur=by.get(r.reviewer_id)||{interviews:0,scores:[],recommendations:{}};cur.interviews++;for(const[k,v]of Object.entries(r.scorecard||{})){if(k==="_recommendation"){if(typeof v==="string")cur.recommendations[v]=(cur.recommendations[v]||0)+1;continue;}if(typeof v==="number")cur.scores.push(v);else if(v&&typeof v==="object"&&typeof(v as any).score==="number")cur.scores.push((v as any).score);}by.set(r.reviewer_id,cur);}return c.json([...by.entries()].map(([reviewerId,v])=>({reviewerId,interviews:v.interviews,averageScore:v.scores.length?v.scores.reduce((a,b)=>a+b,0)/v.scores.length:null,recommendations:v.recommendations})).sort((a,b)=>b.interviews-a.interviews));});

serve({fetch:app.fetch,port:Number(process.env.PORT||4114)});